// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/CSUNetSec/netsec-protobufs/bgpmon/bgpmon.proto

/*
Package bgpmon is a generated protocol buffer package.

It is generated from these files:
	github.com/CSUNetSec/netsec-protobufs/bgpmon/bgpmon.proto

It has these top-level messages:
	Empty
	GoBGPLinkModule
	PrefixByAsNumberModule
	PrefixHijackModule
	ListModulesReply
	RunModuleRequest
	RunModuleReply
	StartModuleRequest
	StartModuleReply
	StopModuleRequest
	CassandraSession
	CockroachSession
	FileSession
	SqliteSession
	CloseSessionRequest
	ListSessionsReply
	OpenSessionRequest
	OpenSessionReply
	WriteRequest
	GetRequest
	GetReply
	ASNumberLocation
	BGPCapture
	IPAddressLocation
	IPPrefix
	Location
	Count
	BGPStats
	PrefixLocation
*/
package bgpmon

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "github.com/CSUNetSec/netsec-protobufs/common"
import bgp "github.com/CSUNetSec/netsec-protobufs/protocol/bgp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

//
// Module Messages
type ModuleType int32

const (
	ModuleType_GOBGP_LINK          ModuleType = 0
	ModuleType_PREFIX_BY_AS_NUMBER ModuleType = 1
	ModuleType_PREFIX_HIJACK       ModuleType = 2
)

var ModuleType_name = map[int32]string{
	0: "GOBGP_LINK",
	1: "PREFIX_BY_AS_NUMBER",
	2: "PREFIX_HIJACK",
}
var ModuleType_value = map[string]int32{
	"GOBGP_LINK":          0,
	"PREFIX_BY_AS_NUMBER": 1,
	"PREFIX_HIJACK":       2,
}

func (x ModuleType) String() string {
	return proto.EnumName(ModuleType_name, int32(x))
}
func (ModuleType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

//
// Session Messages
type SessionType int32

const (
	SessionType_CASSANDRA SessionType = 0
	SessionType_FILE      SessionType = 1
	SessionType_COCKROACH SessionType = 2
	SessionType_SQLITE    SessionType = 3
)

var SessionType_name = map[int32]string{
	0: "CASSANDRA",
	1: "FILE",
	2: "COCKROACH",
	3: "SQLITE",
}
var SessionType_value = map[string]int32{
	"CASSANDRA": 0,
	"FILE":      1,
	"COCKROACH": 2,
	"SQLITE":    3,
}

func (x SessionType) String() string {
	return proto.EnumName(SessionType_name, int32(x))
}
func (SessionType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type WriteRequest_Type int32

const (
	WriteRequest_AS_NUMBER_LOCATION  WriteRequest_Type = 0
	WriteRequest_IP_ADDRESS_LOCATION WriteRequest_Type = 2
	WriteRequest_PREFIX_LOCATION     WriteRequest_Type = 3
	WriteRequest_BGP_CAPTURE         WriteRequest_Type = 4
	WriteRequest_BGP_STATS           WriteRequest_Type = 5
)

var WriteRequest_Type_name = map[int32]string{
	0: "AS_NUMBER_LOCATION",
	2: "IP_ADDRESS_LOCATION",
	3: "PREFIX_LOCATION",
	4: "BGP_CAPTURE",
	5: "BGP_STATS",
}
var WriteRequest_Type_value = map[string]int32{
	"AS_NUMBER_LOCATION":  0,
	"IP_ADDRESS_LOCATION": 2,
	"PREFIX_LOCATION":     3,
	"BGP_CAPTURE":         4,
	"BGP_STATS":           5,
}

func (x WriteRequest_Type) String() string {
	return proto.EnumName(WriteRequest_Type_name, int32(x))
}
func (WriteRequest_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{18, 0} }

type GetRequest_Type int32

const (
	GetRequest_BGP_CAPTURE GetRequest_Type = 0
)

var GetRequest_Type_name = map[int32]string{
	0: "BGP_CAPTURE",
}
var GetRequest_Type_value = map[string]int32{
	"BGP_CAPTURE": 0,
}

func (x GetRequest_Type) String() string {
	return proto.EnumName(GetRequest_Type_name, int32(x))
}
func (GetRequest_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{19, 0} }

type GetReply_Type int32

const (
	GetReply_BGP_CAPTURE GetReply_Type = 0
)

var GetReply_Type_name = map[int32]string{
	0: "BGP_CAPTURE",
}
var GetReply_Type_value = map[string]int32{
	"BGP_CAPTURE": 0,
}

func (x GetReply_Type) String() string {
	return proto.EnumName(GetReply_Type_name, int32(x))
}
func (GetReply_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{20, 0} }

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GoBGPLinkModule struct {
	Address      string   `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	OutSessionId []string `protobuf:"bytes,2,rep,name=out_session_id,json=outSessionId" json:"out_session_id,omitempty"`
}

func (m *GoBGPLinkModule) Reset()                    { *m = GoBGPLinkModule{} }
func (m *GoBGPLinkModule) String() string            { return proto.CompactTextString(m) }
func (*GoBGPLinkModule) ProtoMessage()               {}
func (*GoBGPLinkModule) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GoBGPLinkModule) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *GoBGPLinkModule) GetOutSessionId() []string {
	if m != nil {
		return m.OutSessionId
	}
	return nil
}

type PrefixByAsNumberModule struct {
	StartTime   int64    `protobuf:"varint,1,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	EndTime     int64    `protobuf:"varint,2,opt,name=end_time,json=endTime" json:"end_time,omitempty"`
	InSessionId []string `protobuf:"bytes,3,rep,name=in_session_id,json=inSessionId" json:"in_session_id,omitempty"`
}

func (m *PrefixByAsNumberModule) Reset()                    { *m = PrefixByAsNumberModule{} }
func (m *PrefixByAsNumberModule) String() string            { return proto.CompactTextString(m) }
func (*PrefixByAsNumberModule) ProtoMessage()               {}
func (*PrefixByAsNumberModule) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PrefixByAsNumberModule) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *PrefixByAsNumberModule) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *PrefixByAsNumberModule) GetInSessionId() []string {
	if m != nil {
		return m.InSessionId
	}
	return nil
}

type PrefixHijackModule struct {
	PeriodicSeconds           int32    `protobuf:"varint,1,opt,name=periodic_seconds,json=periodicSeconds" json:"periodic_seconds,omitempty"`
	TimeoutSeconds            int32    `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds" json:"timeout_seconds,omitempty"`
	InSessionId               []string `protobuf:"bytes,3,rep,name=in_session_id,json=inSessionId" json:"in_session_id,omitempty"`
	StartTimeSecondsFromEpoch int64    `protobuf:"varint,4,opt,name=start_time_seconds_from_epoch,json=startTimeSecondsFromEpoch" json:"start_time_seconds_from_epoch,omitempty"`
	LookbackDurationSeconds   int64    `protobuf:"varint,5,opt,name=lookback_duration_seconds,json=lookbackDurationSeconds" json:"lookback_duration_seconds,omitempty"`
}

func (m *PrefixHijackModule) Reset()                    { *m = PrefixHijackModule{} }
func (m *PrefixHijackModule) String() string            { return proto.CompactTextString(m) }
func (*PrefixHijackModule) ProtoMessage()               {}
func (*PrefixHijackModule) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PrefixHijackModule) GetPeriodicSeconds() int32 {
	if m != nil {
		return m.PeriodicSeconds
	}
	return 0
}

func (m *PrefixHijackModule) GetTimeoutSeconds() int32 {
	if m != nil {
		return m.TimeoutSeconds
	}
	return 0
}

func (m *PrefixHijackModule) GetInSessionId() []string {
	if m != nil {
		return m.InSessionId
	}
	return nil
}

func (m *PrefixHijackModule) GetStartTimeSecondsFromEpoch() int64 {
	if m != nil {
		return m.StartTimeSecondsFromEpoch
	}
	return 0
}

func (m *PrefixHijackModule) GetLookbackDurationSeconds() int64 {
	if m != nil {
		return m.LookbackDurationSeconds
	}
	return 0
}

//
// Module Command Messages
type ListModulesReply struct {
	ModuleId []string `protobuf:"bytes,1,rep,name=module_id,json=moduleId" json:"module_id,omitempty"`
}

func (m *ListModulesReply) Reset()                    { *m = ListModulesReply{} }
func (m *ListModulesReply) String() string            { return proto.CompactTextString(m) }
func (*ListModulesReply) ProtoMessage()               {}
func (*ListModulesReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ListModulesReply) GetModuleId() []string {
	if m != nil {
		return m.ModuleId
	}
	return nil
}

type RunModuleRequest struct {
	Type                   ModuleType              `protobuf:"varint,1,opt,name=type,enum=bgpmon.ModuleType" json:"type,omitempty"`
	PrefixByAsNumberModule *PrefixByAsNumberModule `protobuf:"bytes,2,opt,name=prefix_by_as_number_module,json=prefixByAsNumberModule" json:"prefix_by_as_number_module,omitempty"`
	PrefixHijackModule     *PrefixHijackModule     `protobuf:"bytes,3,opt,name=prefix_hijack_module,json=prefixHijackModule" json:"prefix_hijack_module,omitempty"`
}

func (m *RunModuleRequest) Reset()                    { *m = RunModuleRequest{} }
func (m *RunModuleRequest) String() string            { return proto.CompactTextString(m) }
func (*RunModuleRequest) ProtoMessage()               {}
func (*RunModuleRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RunModuleRequest) GetType() ModuleType {
	if m != nil {
		return m.Type
	}
	return ModuleType_GOBGP_LINK
}

func (m *RunModuleRequest) GetPrefixByAsNumberModule() *PrefixByAsNumberModule {
	if m != nil {
		return m.PrefixByAsNumberModule
	}
	return nil
}

func (m *RunModuleRequest) GetPrefixHijackModule() *PrefixHijackModule {
	if m != nil {
		return m.PrefixHijackModule
	}
	return nil
}

type RunModuleReply struct {
	ModuleMessage string `protobuf:"bytes,3,opt,name=module_message,json=moduleMessage" json:"module_message,omitempty"`
}

func (m *RunModuleReply) Reset()                    { *m = RunModuleReply{} }
func (m *RunModuleReply) String() string            { return proto.CompactTextString(m) }
func (*RunModuleReply) ProtoMessage()               {}
func (*RunModuleReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *RunModuleReply) GetModuleMessage() string {
	if m != nil {
		return m.ModuleMessage
	}
	return ""
}

type StartModuleRequest struct {
	Type               ModuleType          `protobuf:"varint,1,opt,name=type,enum=bgpmon.ModuleType" json:"type,omitempty"`
	ModuleId           string              `protobuf:"bytes,2,opt,name=module_id,json=moduleId" json:"module_id,omitempty"`
	GobgpLinkModule    *GoBGPLinkModule    `protobuf:"bytes,3,opt,name=gobgp_link_module,json=gobgpLinkModule" json:"gobgp_link_module,omitempty"`
	PrefixHijackModule *PrefixHijackModule `protobuf:"bytes,4,opt,name=prefix_hijack_module,json=prefixHijackModule" json:"prefix_hijack_module,omitempty"`
}

func (m *StartModuleRequest) Reset()                    { *m = StartModuleRequest{} }
func (m *StartModuleRequest) String() string            { return proto.CompactTextString(m) }
func (*StartModuleRequest) ProtoMessage()               {}
func (*StartModuleRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *StartModuleRequest) GetType() ModuleType {
	if m != nil {
		return m.Type
	}
	return ModuleType_GOBGP_LINK
}

func (m *StartModuleRequest) GetModuleId() string {
	if m != nil {
		return m.ModuleId
	}
	return ""
}

func (m *StartModuleRequest) GetGobgpLinkModule() *GoBGPLinkModule {
	if m != nil {
		return m.GobgpLinkModule
	}
	return nil
}

func (m *StartModuleRequest) GetPrefixHijackModule() *PrefixHijackModule {
	if m != nil {
		return m.PrefixHijackModule
	}
	return nil
}

type StartModuleReply struct {
	ModuleId string `protobuf:"bytes,3,opt,name=module_id,json=moduleId" json:"module_id,omitempty"`
}

func (m *StartModuleReply) Reset()                    { *m = StartModuleReply{} }
func (m *StartModuleReply) String() string            { return proto.CompactTextString(m) }
func (*StartModuleReply) ProtoMessage()               {}
func (*StartModuleReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *StartModuleReply) GetModuleId() string {
	if m != nil {
		return m.ModuleId
	}
	return ""
}

type StopModuleRequest struct {
	ModuleId string `protobuf:"bytes,1,opt,name=module_id,json=moduleId" json:"module_id,omitempty"`
}

func (m *StopModuleRequest) Reset()                    { *m = StopModuleRequest{} }
func (m *StopModuleRequest) String() string            { return proto.CompactTextString(m) }
func (*StopModuleRequest) ProtoMessage()               {}
func (*StopModuleRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *StopModuleRequest) GetModuleId() string {
	if m != nil {
		return m.ModuleId
	}
	return ""
}

type CassandraSession struct {
	Username    string   `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password    string   `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Hosts       []string `protobuf:"bytes,3,rep,name=hosts" json:"hosts,omitempty"`
	WorkerCount uint32   `protobuf:"varint,4,opt,name=workerCount" json:"workerCount,omitempty"`
}

func (m *CassandraSession) Reset()                    { *m = CassandraSession{} }
func (m *CassandraSession) String() string            { return proto.CompactTextString(m) }
func (*CassandraSession) ProtoMessage()               {}
func (*CassandraSession) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *CassandraSession) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CassandraSession) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CassandraSession) GetHosts() []string {
	if m != nil {
		return m.Hosts
	}
	return nil
}

func (m *CassandraSession) GetWorkerCount() uint32 {
	if m != nil {
		return m.WorkerCount
	}
	return 0
}

type CockroachSession struct {
	Username    string   `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password    string   `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Hosts       []string `protobuf:"bytes,3,rep,name=hosts" json:"hosts,omitempty"`
	Port        uint32   `protobuf:"varint,4,opt,name=port" json:"port,omitempty"`
	WorkerCount uint32   `protobuf:"varint,5,opt,name=workerCount" json:"workerCount,omitempty"`
	Certdir     string   `protobuf:"bytes,6,opt,name=certdir" json:"certdir,omitempty"`
}

func (m *CockroachSession) Reset()                    { *m = CockroachSession{} }
func (m *CockroachSession) String() string            { return proto.CompactTextString(m) }
func (*CockroachSession) ProtoMessage()               {}
func (*CockroachSession) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *CockroachSession) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CockroachSession) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CockroachSession) GetHosts() []string {
	if m != nil {
		return m.Hosts
	}
	return nil
}

func (m *CockroachSession) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *CockroachSession) GetWorkerCount() uint32 {
	if m != nil {
		return m.WorkerCount
	}
	return 0
}

func (m *CockroachSession) GetCertdir() string {
	if m != nil {
		return m.Certdir
	}
	return ""
}

type FileSession struct {
	Filename string `protobuf:"bytes,1,opt,name=filename" json:"filename,omitempty"`
}

func (m *FileSession) Reset()                    { *m = FileSession{} }
func (m *FileSession) String() string            { return proto.CompactTextString(m) }
func (*FileSession) ProtoMessage()               {}
func (*FileSession) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *FileSession) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

type SqliteSession struct {
	Filename string `protobuf:"bytes,1,opt,name=filename" json:"filename,omitempty"`
}

func (m *SqliteSession) Reset()                    { *m = SqliteSession{} }
func (m *SqliteSession) String() string            { return proto.CompactTextString(m) }
func (*SqliteSession) ProtoMessage()               {}
func (*SqliteSession) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *SqliteSession) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

//
// Session Command Messages
type CloseSessionRequest struct {
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
}

func (m *CloseSessionRequest) Reset()                    { *m = CloseSessionRequest{} }
func (m *CloseSessionRequest) String() string            { return proto.CompactTextString(m) }
func (*CloseSessionRequest) ProtoMessage()               {}
func (*CloseSessionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *CloseSessionRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type ListSessionsReply struct {
	SessionId []string `protobuf:"bytes,1,rep,name=session_id,json=sessionId" json:"session_id,omitempty"`
}

func (m *ListSessionsReply) Reset()                    { *m = ListSessionsReply{} }
func (m *ListSessionsReply) String() string            { return proto.CompactTextString(m) }
func (*ListSessionsReply) ProtoMessage()               {}
func (*ListSessionsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *ListSessionsReply) GetSessionId() []string {
	if m != nil {
		return m.SessionId
	}
	return nil
}

type OpenSessionRequest struct {
	Type             SessionType       `protobuf:"varint,1,opt,name=type,enum=bgpmon.SessionType" json:"type,omitempty"`
	SessionId        string            `protobuf:"bytes,2,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	CassandraSession *CassandraSession `protobuf:"bytes,3,opt,name=cassandra_session,json=cassandraSession" json:"cassandra_session,omitempty"`
	FileSession      *FileSession      `protobuf:"bytes,4,opt,name=file_session,json=fileSession" json:"file_session,omitempty"`
	CockroachSession *CockroachSession `protobuf:"bytes,5,opt,name=cockroach_session,json=cockroachSession" json:"cockroach_session,omitempty"`
	SqliteSession    *SqliteSession    `protobuf:"bytes,6,opt,name=sqlite_session,json=sqliteSession" json:"sqlite_session,omitempty"`
}

func (m *OpenSessionRequest) Reset()                    { *m = OpenSessionRequest{} }
func (m *OpenSessionRequest) String() string            { return proto.CompactTextString(m) }
func (*OpenSessionRequest) ProtoMessage()               {}
func (*OpenSessionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *OpenSessionRequest) GetType() SessionType {
	if m != nil {
		return m.Type
	}
	return SessionType_CASSANDRA
}

func (m *OpenSessionRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *OpenSessionRequest) GetCassandraSession() *CassandraSession {
	if m != nil {
		return m.CassandraSession
	}
	return nil
}

func (m *OpenSessionRequest) GetFileSession() *FileSession {
	if m != nil {
		return m.FileSession
	}
	return nil
}

func (m *OpenSessionRequest) GetCockroachSession() *CockroachSession {
	if m != nil {
		return m.CockroachSession
	}
	return nil
}

func (m *OpenSessionRequest) GetSqliteSession() *SqliteSession {
	if m != nil {
		return m.SqliteSession
	}
	return nil
}

type OpenSessionReply struct {
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
}

func (m *OpenSessionReply) Reset()                    { *m = OpenSessionReply{} }
func (m *OpenSessionReply) String() string            { return proto.CompactTextString(m) }
func (*OpenSessionReply) ProtoMessage()               {}
func (*OpenSessionReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *OpenSessionReply) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

//
// Write Messages
type WriteRequest struct {
	Type              WriteRequest_Type  `protobuf:"varint,1,opt,name=type,enum=bgpmon.WriteRequest_Type" json:"type,omitempty"`
	SessionId         string             `protobuf:"bytes,2,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	AsNumberLocation  *ASNumberLocation  `protobuf:"bytes,3,opt,name=as_number_location,json=asNumberLocation" json:"as_number_location,omitempty"`
	IpAddressLocation *IPAddressLocation `protobuf:"bytes,5,opt,name=ip_address_location,json=ipAddressLocation" json:"ip_address_location,omitempty"`
	PrefixLocation    *PrefixLocation    `protobuf:"bytes,6,opt,name=prefix_location,json=prefixLocation" json:"prefix_location,omitempty"`
	BgpCapture        *BGPCapture        `protobuf:"bytes,7,opt,name=bgp_capture,json=bgpCapture" json:"bgp_capture,omitempty"`
	BgpStats          *BGPStats          `protobuf:"bytes,8,opt,name=bgp_stats,json=bgpStats" json:"bgp_stats,omitempty"`
}

func (m *WriteRequest) Reset()                    { *m = WriteRequest{} }
func (m *WriteRequest) String() string            { return proto.CompactTextString(m) }
func (*WriteRequest) ProtoMessage()               {}
func (*WriteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *WriteRequest) GetType() WriteRequest_Type {
	if m != nil {
		return m.Type
	}
	return WriteRequest_AS_NUMBER_LOCATION
}

func (m *WriteRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *WriteRequest) GetAsNumberLocation() *ASNumberLocation {
	if m != nil {
		return m.AsNumberLocation
	}
	return nil
}

func (m *WriteRequest) GetIpAddressLocation() *IPAddressLocation {
	if m != nil {
		return m.IpAddressLocation
	}
	return nil
}

func (m *WriteRequest) GetPrefixLocation() *PrefixLocation {
	if m != nil {
		return m.PrefixLocation
	}
	return nil
}

func (m *WriteRequest) GetBgpCapture() *BGPCapture {
	if m != nil {
		return m.BgpCapture
	}
	return nil
}

func (m *WriteRequest) GetBgpStats() *BGPStats {
	if m != nil {
		return m.BgpStats
	}
	return nil
}

//
// Get Messages
type GetRequest struct {
	Type           GetRequest_Type `protobuf:"varint,1,opt,name=type,enum=bgpmon.GetRequest_Type" json:"type,omitempty"`
	SessionId      string          `protobuf:"bytes,2,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	StartTimestamp string          `protobuf:"bytes,3,opt,name=start_timestamp,json=startTimestamp" json:"start_timestamp,omitempty"`
	EndTimestamp   string          `protobuf:"bytes,4,opt,name=end_timestamp,json=endTimestamp" json:"end_timestamp,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *GetRequest) GetType() GetRequest_Type {
	if m != nil {
		return m.Type
	}
	return GetRequest_BGP_CAPTURE
}

func (m *GetRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *GetRequest) GetStartTimestamp() string {
	if m != nil {
		return m.StartTimestamp
	}
	return ""
}

func (m *GetRequest) GetEndTimestamp() string {
	if m != nil {
		return m.EndTimestamp
	}
	return ""
}

type GetReply struct {
	Type         GetReply_Type `protobuf:"varint,1,opt,name=type,enum=bgpmon.GetReply_Type" json:"type,omitempty"`
	Captures     []*BGPCapture `protobuf:"bytes,2,rep,name=captures" json:"captures,omitempty"`
	CollectionId string        `protobuf:"bytes,3,opt,name=collection_id,json=collectionId" json:"collection_id,omitempty"`
}

func (m *GetReply) Reset()                    { *m = GetReply{} }
func (m *GetReply) String() string            { return proto.CompactTextString(m) }
func (*GetReply) ProtoMessage()               {}
func (*GetReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *GetReply) GetType() GetReply_Type {
	if m != nil {
		return m.Type
	}
	return GetReply_BGP_CAPTURE
}

func (m *GetReply) GetCaptures() []*BGPCapture {
	if m != nil {
		return m.Captures
	}
	return nil
}

func (m *GetReply) GetCollectionId() string {
	if m != nil {
		return m.CollectionId
	}
	return ""
}

type ASNumberLocation struct {
	AsNumber    uint32    `protobuf:"varint,1,opt,name=as_number,json=asNumber" json:"as_number,omitempty"`
	MeasureDate string    `protobuf:"bytes,2,opt,name=measure_date,json=measureDate" json:"measure_date,omitempty"`
	Location    *Location `protobuf:"bytes,3,opt,name=location" json:"location,omitempty"`
	Source      string    `protobuf:"bytes,4,opt,name=source" json:"source,omitempty"`
}

func (m *ASNumberLocation) Reset()                    { *m = ASNumberLocation{} }
func (m *ASNumberLocation) String() string            { return proto.CompactTextString(m) }
func (*ASNumberLocation) ProtoMessage()               {}
func (*ASNumberLocation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *ASNumberLocation) GetAsNumber() uint32 {
	if m != nil {
		return m.AsNumber
	}
	return 0
}

func (m *ASNumberLocation) GetMeasureDate() string {
	if m != nil {
		return m.MeasureDate
	}
	return ""
}

func (m *ASNumberLocation) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *ASNumberLocation) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

// a message of Capture type to facilitate the represtation of a
// BGP Update from multuple sources (live/mrt etc) to bgpmon
// and other systems. the inner actual update is defined in protocol/bgp
type BGPCapture struct {
	Timestamp      uint32                   `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	PeerAs         uint32                   `protobuf:"varint,2,opt,name=peer_as,json=peerAs" json:"peer_as,omitempty"`
	LocalAs        uint32                   `protobuf:"varint,3,opt,name=local_as,json=localAs" json:"local_as,omitempty"`
	InterfaceIndex uint32                   `protobuf:"varint,4,opt,name=interface_index,json=interfaceIndex" json:"interface_index,omitempty"`
	AddressFamily  uint32                   `protobuf:"varint,5,opt,name=address_family,json=addressFamily" json:"address_family,omitempty"`
	PeerIp         *common.IPAddressWrapper `protobuf:"bytes,6,opt,name=peer_ip,json=peerIp" json:"peer_ip,omitempty"`
	LocalIp        *common.IPAddressWrapper `protobuf:"bytes,7,opt,name=local_ip,json=localIp" json:"local_ip,omitempty"`
	Update         *bgp.BGPUpdate           `protobuf:"bytes,8,opt,name=update" json:"update,omitempty"`
}

func (m *BGPCapture) Reset()                    { *m = BGPCapture{} }
func (m *BGPCapture) String() string            { return proto.CompactTextString(m) }
func (*BGPCapture) ProtoMessage()               {}
func (*BGPCapture) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *BGPCapture) GetTimestamp() uint32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *BGPCapture) GetPeerAs() uint32 {
	if m != nil {
		return m.PeerAs
	}
	return 0
}

func (m *BGPCapture) GetLocalAs() uint32 {
	if m != nil {
		return m.LocalAs
	}
	return 0
}

func (m *BGPCapture) GetInterfaceIndex() uint32 {
	if m != nil {
		return m.InterfaceIndex
	}
	return 0
}

func (m *BGPCapture) GetAddressFamily() uint32 {
	if m != nil {
		return m.AddressFamily
	}
	return 0
}

func (m *BGPCapture) GetPeerIp() *common.IPAddressWrapper {
	if m != nil {
		return m.PeerIp
	}
	return nil
}

func (m *BGPCapture) GetLocalIp() *common.IPAddressWrapper {
	if m != nil {
		return m.LocalIp
	}
	return nil
}

func (m *BGPCapture) GetUpdate() *bgp.BGPUpdate {
	if m != nil {
		return m.Update
	}
	return nil
}

type IPAddressLocation struct {
	IpAddress   string    `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress" json:"ip_address,omitempty"`
	MeasureDate string    `protobuf:"bytes,2,opt,name=measure_date,json=measureDate" json:"measure_date,omitempty"`
	Location    *Location `protobuf:"bytes,3,opt,name=location" json:"location,omitempty"`
	Source      string    `protobuf:"bytes,4,opt,name=source" json:"source,omitempty"`
}

func (m *IPAddressLocation) Reset()                    { *m = IPAddressLocation{} }
func (m *IPAddressLocation) String() string            { return proto.CompactTextString(m) }
func (*IPAddressLocation) ProtoMessage()               {}
func (*IPAddressLocation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *IPAddressLocation) GetIpAddress() string {
	if m != nil {
		return m.IpAddress
	}
	return ""
}

func (m *IPAddressLocation) GetMeasureDate() string {
	if m != nil {
		return m.MeasureDate
	}
	return ""
}

func (m *IPAddressLocation) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *IPAddressLocation) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

type IPPrefix struct {
	PrefixIpAddress string `protobuf:"bytes,1,opt,name=prefix_ip_address,json=prefixIpAddress" json:"prefix_ip_address,omitempty"`
	PrefixMask      uint32 `protobuf:"varint,2,opt,name=prefix_mask,json=prefixMask" json:"prefix_mask,omitempty"`
}

func (m *IPPrefix) Reset()                    { *m = IPPrefix{} }
func (m *IPPrefix) String() string            { return proto.CompactTextString(m) }
func (*IPPrefix) ProtoMessage()               {}
func (*IPPrefix) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *IPPrefix) GetPrefixIpAddress() string {
	if m != nil {
		return m.PrefixIpAddress
	}
	return ""
}

func (m *IPPrefix) GetPrefixMask() uint32 {
	if m != nil {
		return m.PrefixMask
	}
	return 0
}

type Location struct {
	CountryCode string  `protobuf:"bytes,1,opt,name=country_code,json=countryCode" json:"country_code,omitempty"`
	StateCode   string  `protobuf:"bytes,2,opt,name=state_code,json=stateCode" json:"state_code,omitempty"`
	City        string  `protobuf:"bytes,3,opt,name=city" json:"city,omitempty"`
	Latitude    float64 `protobuf:"fixed64,4,opt,name=latitude" json:"latitude,omitempty"`
	Longitude   float64 `protobuf:"fixed64,5,opt,name=longitude" json:"longitude,omitempty"`
}

func (m *Location) Reset()                    { *m = Location{} }
func (m *Location) String() string            { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()               {}
func (*Location) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *Location) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

func (m *Location) GetStateCode() string {
	if m != nil {
		return m.StateCode
	}
	return ""
}

func (m *Location) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Location) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Location) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type Count struct {
	Count map[string]uint32 `protobuf:"bytes,1,rep,name=count" json:"count,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
}

func (m *Count) Reset()                    { *m = Count{} }
func (m *Count) String() string            { return proto.CompactTextString(m) }
func (*Count) ProtoMessage()               {}
func (*Count) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *Count) GetCount() map[string]uint32 {
	if m != nil {
		return m.Count
	}
	return nil
}

type BGPStats struct {
	CollectorIp          string            `protobuf:"bytes,1,opt,name=collector_ip,json=collectorIp" json:"collector_ip,omitempty"`
	TimeStartSecEpoch    uint64            `protobuf:"varint,2,opt,name=timeStartSecEpoch" json:"timeStartSecEpoch,omitempty"`
	DurationSec          uint32            `protobuf:"varint,3,opt,name=durationSec" json:"durationSec,omitempty"`
	MsgCounts            *Count            `protobuf:"bytes,4,opt,name=msgCounts" json:"msgCounts,omitempty"`
	DestAsToPrefixCounts map[string]*Count `protobuf:"bytes,5,rep,name=destAsToPrefixCounts" json:"destAsToPrefixCounts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DestAsToASPCounts    map[string]*Count `protobuf:"bytes,6,rep,name=destAsToASPCounts" json:"destAsToASPCounts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *BGPStats) Reset()                    { *m = BGPStats{} }
func (m *BGPStats) String() string            { return proto.CompactTextString(m) }
func (*BGPStats) ProtoMessage()               {}
func (*BGPStats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *BGPStats) GetCollectorIp() string {
	if m != nil {
		return m.CollectorIp
	}
	return ""
}

func (m *BGPStats) GetTimeStartSecEpoch() uint64 {
	if m != nil {
		return m.TimeStartSecEpoch
	}
	return 0
}

func (m *BGPStats) GetDurationSec() uint32 {
	if m != nil {
		return m.DurationSec
	}
	return 0
}

func (m *BGPStats) GetMsgCounts() *Count {
	if m != nil {
		return m.MsgCounts
	}
	return nil
}

func (m *BGPStats) GetDestAsToPrefixCounts() map[string]*Count {
	if m != nil {
		return m.DestAsToPrefixCounts
	}
	return nil
}

func (m *BGPStats) GetDestAsToASPCounts() map[string]*Count {
	if m != nil {
		return m.DestAsToASPCounts
	}
	return nil
}

type PrefixLocation struct {
	Prefix      *IPPrefix `protobuf:"bytes,1,opt,name=prefix" json:"prefix,omitempty"`
	MeasureDate string    `protobuf:"bytes,2,opt,name=measure_date,json=measureDate" json:"measure_date,omitempty"`
	Location    *Location `protobuf:"bytes,3,opt,name=location" json:"location,omitempty"`
	Source      string    `protobuf:"bytes,4,opt,name=source" json:"source,omitempty"`
}

func (m *PrefixLocation) Reset()                    { *m = PrefixLocation{} }
func (m *PrefixLocation) String() string            { return proto.CompactTextString(m) }
func (*PrefixLocation) ProtoMessage()               {}
func (*PrefixLocation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *PrefixLocation) GetPrefix() *IPPrefix {
	if m != nil {
		return m.Prefix
	}
	return nil
}

func (m *PrefixLocation) GetMeasureDate() string {
	if m != nil {
		return m.MeasureDate
	}
	return ""
}

func (m *PrefixLocation) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *PrefixLocation) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "bgpmon.Empty")
	proto.RegisterType((*GoBGPLinkModule)(nil), "bgpmon.GoBGPLinkModule")
	proto.RegisterType((*PrefixByAsNumberModule)(nil), "bgpmon.PrefixByAsNumberModule")
	proto.RegisterType((*PrefixHijackModule)(nil), "bgpmon.PrefixHijackModule")
	proto.RegisterType((*ListModulesReply)(nil), "bgpmon.ListModulesReply")
	proto.RegisterType((*RunModuleRequest)(nil), "bgpmon.RunModuleRequest")
	proto.RegisterType((*RunModuleReply)(nil), "bgpmon.RunModuleReply")
	proto.RegisterType((*StartModuleRequest)(nil), "bgpmon.StartModuleRequest")
	proto.RegisterType((*StartModuleReply)(nil), "bgpmon.StartModuleReply")
	proto.RegisterType((*StopModuleRequest)(nil), "bgpmon.StopModuleRequest")
	proto.RegisterType((*CassandraSession)(nil), "bgpmon.CassandraSession")
	proto.RegisterType((*CockroachSession)(nil), "bgpmon.CockroachSession")
	proto.RegisterType((*FileSession)(nil), "bgpmon.FileSession")
	proto.RegisterType((*SqliteSession)(nil), "bgpmon.SqliteSession")
	proto.RegisterType((*CloseSessionRequest)(nil), "bgpmon.CloseSessionRequest")
	proto.RegisterType((*ListSessionsReply)(nil), "bgpmon.ListSessionsReply")
	proto.RegisterType((*OpenSessionRequest)(nil), "bgpmon.OpenSessionRequest")
	proto.RegisterType((*OpenSessionReply)(nil), "bgpmon.OpenSessionReply")
	proto.RegisterType((*WriteRequest)(nil), "bgpmon.WriteRequest")
	proto.RegisterType((*GetRequest)(nil), "bgpmon.GetRequest")
	proto.RegisterType((*GetReply)(nil), "bgpmon.GetReply")
	proto.RegisterType((*ASNumberLocation)(nil), "bgpmon.ASNumberLocation")
	proto.RegisterType((*BGPCapture)(nil), "bgpmon.BGPCapture")
	proto.RegisterType((*IPAddressLocation)(nil), "bgpmon.IPAddressLocation")
	proto.RegisterType((*IPPrefix)(nil), "bgpmon.IPPrefix")
	proto.RegisterType((*Location)(nil), "bgpmon.Location")
	proto.RegisterType((*Count)(nil), "bgpmon.Count")
	proto.RegisterType((*BGPStats)(nil), "bgpmon.BGPStats")
	proto.RegisterType((*PrefixLocation)(nil), "bgpmon.PrefixLocation")
	proto.RegisterEnum("bgpmon.ModuleType", ModuleType_name, ModuleType_value)
	proto.RegisterEnum("bgpmon.SessionType", SessionType_name, SessionType_value)
	proto.RegisterEnum("bgpmon.WriteRequest_Type", WriteRequest_Type_name, WriteRequest_Type_value)
	proto.RegisterEnum("bgpmon.GetRequest_Type", GetRequest_Type_name, GetRequest_Type_value)
	proto.RegisterEnum("bgpmon.GetReply_Type", GetReply_Type_name, GetReply_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Bgpmond service

type BgpmondClient interface {
	CloseSession(ctx context.Context, in *CloseSessionRequest, opts ...grpc.CallOption) (*Empty, error)
	ListModules(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListModulesReply, error)
	ListSessions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListSessionsReply, error)
	RunModule(ctx context.Context, in *RunModuleRequest, opts ...grpc.CallOption) (*RunModuleReply, error)
	StartModule(ctx context.Context, in *StartModuleRequest, opts ...grpc.CallOption) (*StartModuleReply, error)
	StopModule(ctx context.Context, in *StopModuleRequest, opts ...grpc.CallOption) (*Empty, error)
	OpenSession(ctx context.Context, in *OpenSessionRequest, opts ...grpc.CallOption) (*OpenSessionReply, error)
	Write(ctx context.Context, opts ...grpc.CallOption) (Bgpmond_WriteClient, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (Bgpmond_GetClient, error)
}

type bgpmondClient struct {
	cc *grpc.ClientConn
}

func NewBgpmondClient(cc *grpc.ClientConn) BgpmondClient {
	return &bgpmondClient{cc}
}

func (c *bgpmondClient) CloseSession(ctx context.Context, in *CloseSessionRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/bgpmon.Bgpmond/CloseSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bgpmondClient) ListModules(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListModulesReply, error) {
	out := new(ListModulesReply)
	err := grpc.Invoke(ctx, "/bgpmon.Bgpmond/ListModules", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bgpmondClient) ListSessions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListSessionsReply, error) {
	out := new(ListSessionsReply)
	err := grpc.Invoke(ctx, "/bgpmon.Bgpmond/ListSessions", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bgpmondClient) RunModule(ctx context.Context, in *RunModuleRequest, opts ...grpc.CallOption) (*RunModuleReply, error) {
	out := new(RunModuleReply)
	err := grpc.Invoke(ctx, "/bgpmon.Bgpmond/RunModule", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bgpmondClient) StartModule(ctx context.Context, in *StartModuleRequest, opts ...grpc.CallOption) (*StartModuleReply, error) {
	out := new(StartModuleReply)
	err := grpc.Invoke(ctx, "/bgpmon.Bgpmond/StartModule", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bgpmondClient) StopModule(ctx context.Context, in *StopModuleRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/bgpmon.Bgpmond/StopModule", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bgpmondClient) OpenSession(ctx context.Context, in *OpenSessionRequest, opts ...grpc.CallOption) (*OpenSessionReply, error) {
	out := new(OpenSessionReply)
	err := grpc.Invoke(ctx, "/bgpmon.Bgpmond/OpenSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bgpmondClient) Write(ctx context.Context, opts ...grpc.CallOption) (Bgpmond_WriteClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Bgpmond_serviceDesc.Streams[0], c.cc, "/bgpmon.Bgpmond/Write", opts...)
	if err != nil {
		return nil, err
	}
	x := &bgpmondWriteClient{stream}
	return x, nil
}

type Bgpmond_WriteClient interface {
	Send(*WriteRequest) error
	CloseAndRecv() (*Empty, error)
	grpc.ClientStream
}

type bgpmondWriteClient struct {
	grpc.ClientStream
}

func (x *bgpmondWriteClient) Send(m *WriteRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *bgpmondWriteClient) CloseAndRecv() (*Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *bgpmondClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (Bgpmond_GetClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Bgpmond_serviceDesc.Streams[1], c.cc, "/bgpmon.Bgpmond/Get", opts...)
	if err != nil {
		return nil, err
	}
	x := &bgpmondGetClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Bgpmond_GetClient interface {
	Recv() (*GetReply, error)
	grpc.ClientStream
}

type bgpmondGetClient struct {
	grpc.ClientStream
}

func (x *bgpmondGetClient) Recv() (*GetReply, error) {
	m := new(GetReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Bgpmond service

type BgpmondServer interface {
	CloseSession(context.Context, *CloseSessionRequest) (*Empty, error)
	ListModules(context.Context, *Empty) (*ListModulesReply, error)
	ListSessions(context.Context, *Empty) (*ListSessionsReply, error)
	RunModule(context.Context, *RunModuleRequest) (*RunModuleReply, error)
	StartModule(context.Context, *StartModuleRequest) (*StartModuleReply, error)
	StopModule(context.Context, *StopModuleRequest) (*Empty, error)
	OpenSession(context.Context, *OpenSessionRequest) (*OpenSessionReply, error)
	Write(Bgpmond_WriteServer) error
	Get(*GetRequest, Bgpmond_GetServer) error
}

func RegisterBgpmondServer(s *grpc.Server, srv BgpmondServer) {
	s.RegisterService(&_Bgpmond_serviceDesc, srv)
}

func _Bgpmond_CloseSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BgpmondServer).CloseSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bgpmon.Bgpmond/CloseSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BgpmondServer).CloseSession(ctx, req.(*CloseSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bgpmond_ListModules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BgpmondServer).ListModules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bgpmon.Bgpmond/ListModules",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BgpmondServer).ListModules(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bgpmond_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BgpmondServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bgpmon.Bgpmond/ListSessions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BgpmondServer).ListSessions(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bgpmond_RunModule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunModuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BgpmondServer).RunModule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bgpmon.Bgpmond/RunModule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BgpmondServer).RunModule(ctx, req.(*RunModuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bgpmond_StartModule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartModuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BgpmondServer).StartModule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bgpmon.Bgpmond/StartModule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BgpmondServer).StartModule(ctx, req.(*StartModuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bgpmond_StopModule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopModuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BgpmondServer).StopModule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bgpmon.Bgpmond/StopModule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BgpmondServer).StopModule(ctx, req.(*StopModuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bgpmond_OpenSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BgpmondServer).OpenSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bgpmon.Bgpmond/OpenSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BgpmondServer).OpenSession(ctx, req.(*OpenSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bgpmond_Write_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BgpmondServer).Write(&bgpmondWriteServer{stream})
}

type Bgpmond_WriteServer interface {
	SendAndClose(*Empty) error
	Recv() (*WriteRequest, error)
	grpc.ServerStream
}

type bgpmondWriteServer struct {
	grpc.ServerStream
}

func (x *bgpmondWriteServer) SendAndClose(m *Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *bgpmondWriteServer) Recv() (*WriteRequest, error) {
	m := new(WriteRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Bgpmond_Get_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BgpmondServer).Get(m, &bgpmondGetServer{stream})
}

type Bgpmond_GetServer interface {
	Send(*GetReply) error
	grpc.ServerStream
}

type bgpmondGetServer struct {
	grpc.ServerStream
}

func (x *bgpmondGetServer) Send(m *GetReply) error {
	return x.ServerStream.SendMsg(m)
}

var _Bgpmond_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bgpmon.Bgpmond",
	HandlerType: (*BgpmondServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CloseSession",
			Handler:    _Bgpmond_CloseSession_Handler,
		},
		{
			MethodName: "ListModules",
			Handler:    _Bgpmond_ListModules_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _Bgpmond_ListSessions_Handler,
		},
		{
			MethodName: "RunModule",
			Handler:    _Bgpmond_RunModule_Handler,
		},
		{
			MethodName: "StartModule",
			Handler:    _Bgpmond_StartModule_Handler,
		},
		{
			MethodName: "StopModule",
			Handler:    _Bgpmond_StopModule_Handler,
		},
		{
			MethodName: "OpenSession",
			Handler:    _Bgpmond_OpenSession_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Write",
			Handler:       _Bgpmond_Write_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Get",
			Handler:       _Bgpmond_Get_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "github.com/CSUNetSec/netsec-protobufs/bgpmon/bgpmon.proto",
}

func init() {
	proto.RegisterFile("github.com/CSUNetSec/netsec-protobufs/bgpmon/bgpmon.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 1985 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x18, 0x4b, 0x73, 0x1b, 0x49,
	0xd9, 0x7a, 0x5a, 0xfa, 0x64, 0xc9, 0xa3, 0x76, 0xd6, 0x0f, 0x2d, 0x0b, 0xd9, 0x59, 0xd8, 0xbc,
	0x36, 0x76, 0x36, 0xa1, 0x20, 0xa4, 0x52, 0xb5, 0xc8, 0xb2, 0xec, 0x88, 0x38, 0xb6, 0x76, 0xc6,
	0x26, 0xc0, 0x81, 0xa9, 0xd1, 0x4c, 0xdb, 0x1e, 0x3c, 0x9a, 0x99, 0x4c, 0xb7, 0x76, 0x57, 0xd7,
	0x3d, 0x72, 0xe0, 0x4c, 0xc1, 0x91, 0x13, 0x37, 0x7e, 0x01, 0xfc, 0x15, 0x0e, 0x1c, 0xf9, 0x11,
	0x54, 0x3f, 0xa6, 0xe7, 0x21, 0xb9, 0xca, 0x2c, 0x45, 0x0e, 0x89, 0xd5, 0xdf, 0xab, 0xbf, 0x77,
	0x7f, 0xdf, 0xc0, 0xcf, 0x2e, 0x3d, 0x7a, 0x35, 0x9b, 0xec, 0x3a, 0xe1, 0x74, 0x6f, 0x60, 0x9e,
	0x9f, 0x60, 0x6a, 0x62, 0x67, 0x2f, 0xc0, 0x94, 0x60, 0xe7, 0x71, 0x14, 0x87, 0x34, 0x9c, 0xcc,
	0x2e, 0xc8, 0xde, 0xe4, 0x32, 0x9a, 0x86, 0x81, 0xfc, 0xb3, 0xcb, 0xe1, 0xa8, 0x2e, 0x4e, 0xbd,
	0x5b, 0x8a, 0x70, 0xc2, 0x29, 0x13, 0x21, 0xfe, 0x08, 0x11, 0xbd, 0x97, 0xb7, 0x63, 0xe5, 0xbf,
	0x9c, 0xd0, 0x67, 0xf7, 0xb3, 0x7f, 0x82, 0x5b, 0x5f, 0x85, 0xda, 0x70, 0x1a, 0xd1, 0xb9, 0xfe,
	0x25, 0xac, 0x1f, 0x85, 0xfb, 0x47, 0xe3, 0x63, 0x2f, 0xb8, 0x7e, 0x13, 0xba, 0x33, 0x1f, 0xa3,
	0x6d, 0x58, 0xb5, 0x5d, 0x37, 0xc6, 0x84, 0x6c, 0x97, 0xee, 0x96, 0xee, 0x37, 0x8d, 0xe4, 0x88,
	0x7e, 0x08, 0x9d, 0x70, 0x46, 0x2d, 0x82, 0x09, 0xf1, 0xc2, 0xc0, 0xf2, 0xdc, 0xed, 0xf2, 0xdd,
	0xca, 0xfd, 0xa6, 0xb1, 0x16, 0xce, 0xa8, 0x29, 0x80, 0x23, 0x57, 0xff, 0x0a, 0x36, 0xc7, 0x31,
	0xbe, 0xf0, 0xbe, 0xd9, 0x9f, 0xf7, 0xc9, 0xc9, 0x6c, 0x3a, 0xc1, 0xb1, 0x94, 0xfc, 0x11, 0x00,
	0xa1, 0x76, 0x4c, 0x2d, 0xea, 0x4d, 0x31, 0x17, 0x5e, 0x31, 0x9a, 0x1c, 0x72, 0xe6, 0x4d, 0x31,
	0xda, 0x81, 0x06, 0x0e, 0x5c, 0x81, 0x2c, 0x73, 0xe4, 0x2a, 0x0e, 0x5c, 0x8e, 0xd2, 0xa1, 0xed,
	0x05, 0xd9, 0x8b, 0x2b, 0xfc, 0xe2, 0x96, 0x17, 0xa4, 0xf7, 0xfe, 0xbe, 0x0c, 0x48, 0x5c, 0xfc,
	0xca, 0xfb, 0x9d, 0xed, 0x24, 0xe6, 0x3c, 0x00, 0x2d, 0xc2, 0xb1, 0x17, 0xba, 0x9e, 0x63, 0x11,
	0xec, 0x84, 0x81, 0x2b, 0xec, 0xaa, 0x19, 0xeb, 0x09, 0xdc, 0x14, 0x60, 0x74, 0x0f, 0xd6, 0xd9,
	0xe5, 0xc2, 0x46, 0x41, 0x59, 0xe6, 0x94, 0x1d, 0x09, 0x4e, 0x08, 0x6f, 0xa1, 0x0e, 0xfa, 0x39,
	0x7c, 0x94, 0x1a, 0x9b, 0xc8, 0xb3, 0x2e, 0xe2, 0x70, 0x6a, 0xe1, 0x28, 0x74, 0xae, 0xb6, 0xab,
	0xdc, 0xc4, 0x1d, 0x65, 0xbf, 0x14, 0x7e, 0x18, 0x87, 0xd3, 0x21, 0x23, 0x40, 0x2f, 0x60, 0xc7,
	0x0f, 0xc3, 0xeb, 0x89, 0xed, 0x5c, 0x5b, 0xee, 0x2c, 0xb6, 0x29, 0xbb, 0x2c, 0x51, 0xac, 0xc6,
	0xb9, 0xb7, 0x12, 0x82, 0x03, 0x89, 0x97, 0x42, 0xf4, 0x3d, 0xd0, 0x8e, 0x3d, 0x42, 0x85, 0x0f,
	0x88, 0x81, 0x23, 0x7f, 0x8e, 0x3e, 0x84, 0xe6, 0x94, 0x9f, 0x99, 0xc6, 0x25, 0xae, 0x71, 0x43,
	0x00, 0x46, 0xae, 0xfe, 0xaf, 0x12, 0x68, 0xc6, 0x2c, 0x10, 0x0c, 0x06, 0x7e, 0x37, 0xc3, 0x84,
	0xa2, 0x4f, 0xa1, 0x4a, 0xe7, 0x91, 0x08, 0x55, 0xe7, 0x29, 0xda, 0x95, 0x49, 0x2c, 0x88, 0xce,
	0xe6, 0x11, 0x36, 0x38, 0x1e, 0xfd, 0x06, 0x7a, 0x11, 0xf7, 0xbc, 0x35, 0x99, 0x5b, 0x36, 0xb1,
	0x02, 0x1e, 0x75, 0x4b, 0x08, 0xe7, 0x3e, 0x6c, 0x3d, 0xfd, 0x7e, 0xc2, 0xbd, 0x3c, 0x39, 0x8c,
	0xcd, 0x68, 0x79, 0xd2, 0x1c, 0xc3, 0x1d, 0x29, 0xfb, 0x8a, 0x87, 0x35, 0x91, 0x5a, 0xe1, 0x52,
	0x7b, 0x79, 0xa9, 0xd9, 0xc8, 0x1b, 0x28, 0x5a, 0x80, 0xe9, 0x3f, 0x85, 0x4e, 0xc6, 0x4a, 0xe6,
	0x95, 0x1f, 0x41, 0x47, 0x7a, 0x65, 0x8a, 0x09, 0xb1, 0x2f, 0x85, 0xe4, 0xa6, 0xd1, 0x16, 0xd0,
	0x37, 0x02, 0xa8, 0xff, 0xbb, 0x04, 0xc8, 0x64, 0xa1, 0xfa, 0x6e, 0x1e, 0xca, 0xf9, 0xbe, 0xcc,
	0x2f, 0x50, 0xbe, 0x47, 0x03, 0xe8, 0x5e, 0x86, 0x93, 0xcb, 0xc8, 0xf2, 0xbd, 0xa0, 0x60, 0xdf,
	0x56, 0x22, 0xb1, 0x50, 0xa5, 0xc6, 0x3a, 0xe7, 0xc8, 0x94, 0xed, 0x4d, 0x7e, 0xaa, 0x7e, 0x27,
	0x3f, 0xed, 0x81, 0x96, 0xb3, 0x76, 0x21, 0x7f, 0x2a, 0x79, 0x1b, 0xf4, 0x27, 0xd0, 0x35, 0x69,
	0x18, 0xe5, 0xbd, 0x53, 0xc8, 0xb8, 0x3c, 0xc7, 0xb7, 0x25, 0xd0, 0x06, 0x36, 0x21, 0x76, 0xe0,
	0xc6, 0xb6, 0xac, 0x1b, 0xd4, 0x83, 0xc6, 0x8c, 0xe0, 0x38, 0xb0, 0x65, 0x83, 0x68, 0x1a, 0xea,
	0xcc, 0x70, 0x91, 0x4d, 0xc8, 0xd7, 0x61, 0xac, 0x5c, 0x98, 0x9c, 0xd1, 0x1d, 0xa8, 0x5d, 0x85,
	0x84, 0x12, 0x59, 0x89, 0xe2, 0x80, 0xee, 0x42, 0xeb, 0xeb, 0x30, 0xbe, 0xc6, 0xf1, 0x20, 0x9c,
	0x05, 0x94, 0xbb, 0xa2, 0x6d, 0x64, 0x41, 0xfa, 0xdf, 0x98, 0x12, 0xa1, 0x73, 0x1d, 0x87, 0xb6,
	0x73, 0xf5, 0xff, 0x51, 0x02, 0x41, 0x35, 0x0a, 0xe3, 0xe4, 0x76, 0xfe, 0xbb, 0xa8, 0x58, 0x6d,
	0x41, 0x31, 0xd6, 0x85, 0x1d, 0x1c, 0x53, 0xd7, 0x8b, 0xb7, 0xeb, 0xa2, 0x0b, 0xcb, 0xa3, 0xfe,
	0x00, 0x5a, 0x87, 0x9e, 0x8f, 0x33, 0xca, 0x5e, 0x78, 0x3e, 0xce, 0x2a, 0x9b, 0x9c, 0xf5, 0x47,
	0xd0, 0x36, 0xdf, 0xf9, 0x1e, 0xbd, 0x15, 0xf1, 0x8f, 0x61, 0x63, 0xe0, 0x87, 0x24, 0xa1, 0x4d,
	0x62, 0xc8, 0x9a, 0x76, 0xda, 0xe8, 0x04, 0x53, 0x93, 0xa8, 0xae, 0xfb, 0x14, 0xba, 0xac, 0xd1,
	0x48, 0x26, 0xd9, 0x69, 0x8a, 0x3c, 0x95, 0x3c, 0xcf, 0x3f, 0xcb, 0x80, 0x4e, 0x23, 0x1c, 0x14,
	0x6e, 0xba, 0x97, 0xab, 0xa5, 0x8d, 0x24, 0x63, 0x25, 0x55, 0xa6, 0x98, 0xf2, 0xe2, 0xcb, 0x05,
	0x95, 0xd0, 0x10, 0xba, 0x4e, 0x92, 0x57, 0x49, 0x93, 0x96, 0xe5, 0xb4, 0x9d, 0x08, 0x2d, 0x26,
	0x9e, 0xa1, 0x39, 0xc5, 0x54, 0xfc, 0x09, 0xac, 0x31, 0xdf, 0x28, 0x09, 0xa2, 0x90, 0x94, 0x5a,
	0x99, 0x18, 0x18, 0xad, 0x8b, 0x4c, 0x40, 0xd8, 0xf5, 0x49, 0x46, 0x29, 0xe6, 0x5a, 0xe1, 0xfa,
	0x42, 0xca, 0x19, 0x9a, 0x53, 0x4c, 0xc2, 0x97, 0xd0, 0x21, 0x3c, 0x76, 0x4a, 0x46, 0x9d, 0xcb,
	0xf8, 0x40, 0xf9, 0x25, 0x1b, 0x59, 0xa3, 0x4d, 0xb2, 0x47, 0xfd, 0x73, 0xd0, 0x72, 0x1e, 0x5e,
	0x16, 0x95, 0x42, 0x24, 0xbf, 0xad, 0xc2, 0xda, 0xdb, 0xd8, 0xa3, 0xaa, 0x7a, 0x1f, 0xe7, 0xe2,
	0xb1, 0x93, 0xdc, 0x9b, 0xa5, 0xd9, 0xbd, 0x7d, 0x54, 0x0e, 0x01, 0xa5, 0x2f, 0x83, 0x1f, 0x3a,
	0xfc, 0xb9, 0x2a, 0x86, 0xa5, 0x6f, 0x8a, 0xde, 0x7f, 0x2c, 0xf1, 0x86, 0x66, 0x93, 0x3c, 0x04,
	0x8d, 0x60, 0xc3, 0x8b, 0x2c, 0x39, 0x92, 0xa4, 0x82, 0x84, 0x83, 0x95, 0x92, 0xa3, 0x71, 0x5f,
	0x50, 0x28, 0x49, 0x5d, 0x2f, 0x2a, 0x80, 0xd0, 0x17, 0xb0, 0x2e, 0x5b, 0xa6, 0x12, 0x23, 0x7c,
	0xbc, 0x99, 0xef, 0x96, 0x4a, 0x46, 0x27, 0xca, 0x9d, 0xd1, 0x33, 0x68, 0xb1, 0xb6, 0xed, 0xd8,
	0x11, 0x9d, 0xc5, 0x78, 0x7b, 0x95, 0x33, 0xab, 0x47, 0x60, 0xff, 0x68, 0x3c, 0x10, 0x18, 0x03,
	0x26, 0x97, 0x91, 0xfc, 0x8d, 0x1e, 0x43, 0x93, 0x31, 0x11, 0x6a, 0x53, 0xb2, 0xdd, 0xe0, 0x2c,
	0x5a, 0x86, 0xc5, 0x64, 0x70, 0xa3, 0x31, 0xb9, 0x8c, 0xf8, 0x2f, 0xdd, 0x87, 0x2a, 0x73, 0x32,
	0xda, 0x04, 0xd4, 0x37, 0xad, 0x93, 0xf3, 0x37, 0xfb, 0x43, 0xc3, 0x3a, 0x3e, 0x1d, 0xf4, 0xcf,
	0x46, 0xa7, 0x27, 0xda, 0x0a, 0xda, 0x82, 0x8d, 0xd1, 0xd8, 0xea, 0x1f, 0x1c, 0x18, 0x43, 0xd3,
	0x4c, 0x11, 0x65, 0xb4, 0x01, 0xeb, 0x63, 0x63, 0x78, 0x38, 0xfa, 0x55, 0x0a, 0xac, 0xa0, 0x75,
	0x68, 0xed, 0x1f, 0x8d, 0xad, 0x41, 0x7f, 0x7c, 0x76, 0x6e, 0x0c, 0xb5, 0x2a, 0x6a, 0x43, 0x93,
	0x01, 0xcc, 0xb3, 0xfe, 0x99, 0xa9, 0xd5, 0xf4, 0x7f, 0x94, 0x00, 0x8e, 0x30, 0x4d, 0x52, 0xe0,
	0x51, 0x2e, 0x05, 0xd2, 0xc7, 0x48, 0x51, 0xfc, 0x17, 0x09, 0x70, 0x0f, 0xd6, 0xd3, 0x81, 0x88,
	0x50, 0x7b, 0x1a, 0xc9, 0x47, 0xa4, 0xa3, 0x46, 0x20, 0x0e, 0x45, 0x9f, 0x40, 0x3b, 0x99, 0x03,
	0x05, 0x59, 0x95, 0x93, 0xad, 0xc9, 0x61, 0x90, 0xc3, 0xf4, 0x2d, 0xe9, 0x96, 0x82, 0x41, 0x2b,
	0xfa, 0x5f, 0x4a, 0xd0, 0xe0, 0xfa, 0xb1, 0x94, 0x7f, 0x90, 0xd3, 0xff, 0x83, 0x9c, 0xfe, 0x91,
	0x3f, 0xcf, 0x6a, 0xbf, 0x0b, 0x0d, 0x19, 0x47, 0xc2, 0xc7, 0xda, 0xe5, 0x81, 0x54, 0x34, 0x4c,
	0x4b, 0x27, 0xf4, 0x7d, 0xec, 0x50, 0x35, 0x03, 0x72, 0x2d, 0x53, 0xe0, 0xc8, 0xbd, 0x59, 0xcb,
	0x3f, 0x96, 0x40, 0x2b, 0x26, 0x3b, 0x7b, 0x2e, 0x55, 0x89, 0x70, 0x95, 0xdb, 0x46, 0x23, 0xc9,
	0x7f, 0xf4, 0x31, 0xac, 0x4d, 0xb1, 0x4d, 0x66, 0x31, 0xb6, 0x5c, 0x9b, 0x62, 0xe9, 0xdf, 0x96,
	0x84, 0x1d, 0xd8, 0x14, 0xa3, 0xcf, 0xa0, 0x51, 0x28, 0x2c, 0x95, 0x58, 0x2a, 0x85, 0x15, 0x05,
	0xda, 0x84, 0x3a, 0x09, 0x67, 0xb1, 0x83, 0xa5, 0x7f, 0xe5, 0x49, 0xff, 0x7b, 0x19, 0x20, 0xb5,
	0x18, 0x7d, 0x0f, 0x9a, 0x69, 0x24, 0x84, 0x52, 0x29, 0x00, 0x6d, 0xc1, 0x6a, 0x84, 0x71, 0x6c,
	0xd9, 0x62, 0x54, 0x6e, 0x1b, 0x75, 0x76, 0xec, 0x13, 0x36, 0xcc, 0xb3, 0x9b, 0x7c, 0x86, 0xa9,
	0x70, 0xcc, 0x2a, 0x3f, 0xf7, 0xf9, 0x98, 0xed, 0x05, 0x14, 0xc7, 0x17, 0xb6, 0x83, 0x2d, 0x2f,
	0x70, 0xf1, 0x37, 0xf2, 0x6d, 0xec, 0x28, 0xf0, 0x88, 0x41, 0xd9, 0x68, 0x96, 0xd4, 0xf9, 0x85,
	0x3d, 0xf5, 0xfc, 0xb9, 0x7c, 0x28, 0xdb, 0x12, 0x7a, 0xc8, 0x81, 0xe8, 0x73, 0xa9, 0x83, 0x17,
	0xc9, 0xf2, 0xdd, 0xde, 0x95, 0xab, 0x92, 0xea, 0x02, 0x6f, 0x63, 0x3b, 0x8a, 0x70, 0x2c, 0xb4,
	0x1b, 0x45, 0xe8, 0x59, 0xa2, 0x9d, 0x17, 0xc9, 0xaa, 0xbd, 0x99, 0x47, 0xe8, 0x3d, 0x8a, 0xd0,
	0xa7, 0x50, 0x9f, 0x45, 0xdc, 0xf7, 0xa2, 0x6a, 0x3b, 0xcc, 0xb9, 0x2c, 0x39, 0xce, 0x39, 0xd4,
	0x90, 0x58, 0xfd, 0xcf, 0x25, 0xe8, 0x2e, 0xf4, 0x1f, 0x56, 0x1d, 0x69, 0xdf, 0x4a, 0xba, 0xaf,
	0xea, 0x49, 0xef, 0x2f, 0xbc, 0x6f, 0xa1, 0x31, 0x1a, 0x8b, 0xbe, 0x86, 0x1e, 0x42, 0x57, 0x36,
	0xc0, 0x05, 0xd5, 0x64, 0x67, 0x1c, 0x29, 0x05, 0x7f, 0x00, 0x2d, 0x49, 0x3b, 0xb5, 0xc9, 0xb5,
	0x8c, 0x36, 0x08, 0xd0, 0x1b, 0x9b, 0x5c, 0xeb, 0x7f, 0x2a, 0x41, 0x43, 0x59, 0xfb, 0x31, 0xac,
	0x39, 0x6c, 0x8e, 0x89, 0xe7, 0x96, 0x13, 0xba, 0xc9, 0xb0, 0xd1, 0x92, 0xb0, 0x41, 0xe8, 0x26,
	0xdb, 0x20, 0xc5, 0x82, 0x20, 0x69, 0x17, 0x0c, 0xc2, 0xd1, 0x08, 0xaa, 0x8e, 0x47, 0xe7, 0xb2,
	0xac, 0xf8, 0x6f, 0x36, 0xbe, 0xf8, 0x36, 0xf5, 0xe8, 0xcc, 0x15, 0x56, 0x95, 0x0c, 0x75, 0x66,
	0x79, 0xea, 0x87, 0xc1, 0xa5, 0x40, 0xd6, 0x38, 0x32, 0x05, 0xe8, 0xef, 0xa0, 0x26, 0xe6, 0xaa,
	0x5d, 0xa8, 0x71, 0x25, 0xf8, 0x54, 0x92, 0x7b, 0x91, 0x67, 0x01, 0x15, 0xff, 0x0f, 0x99, 0x8a,
	0x86, 0x20, 0xeb, 0x3d, 0x07, 0x48, 0x81, 0x48, 0x83, 0xca, 0x35, 0x9e, 0x4b, 0x6b, 0xd8, 0x4f,
	0x36, 0xf3, 0x7d, 0x65, 0xfb, 0x33, 0x2c, 0x1d, 0x22, 0x0e, 0x2f, 0xca, 0xcf, 0x4b, 0xfa, 0x1f,
	0xaa, 0xd0, 0x48, 0xfa, 0xb9, 0xf0, 0x07, 0x6f, 0x0c, 0x21, 0x4f, 0x54, 0xe5, 0x0f, 0x09, 0x1b,
	0x45, 0xe8, 0x33, 0xe8, 0xb2, 0xba, 0xe2, 0x63, 0xb7, 0x89, 0x1d, 0xbe, 0x03, 0x72, 0xa9, 0x55,
	0x63, 0x11, 0xc1, 0x26, 0x48, 0x37, 0xdd, 0xf9, 0x64, 0x89, 0x65, 0x41, 0xe8, 0x11, 0x34, 0xa7,
	0xe4, 0x92, 0x2b, 0x4f, 0xe4, 0xf0, 0xd2, 0xce, 0x59, 0x6b, 0xa4, 0x78, 0xf4, 0x5b, 0xb8, 0xe3,
	0x62, 0x42, 0xfb, 0xe4, 0x2c, 0x14, 0xb9, 0x21, 0xf9, 0x6a, 0xdc, 0x4b, 0x0f, 0x8b, 0xef, 0xd3,
	0xee, 0xc1, 0x12, 0x62, 0xe1, 0xb7, 0xa5, 0x72, 0xd0, 0x39, 0x74, 0x13, 0x78, 0xdf, 0x1c, 0x4b,
	0xe1, 0x75, 0x2e, 0xfc, 0xde, 0x8d, 0xc2, 0x15, 0xa5, 0x90, 0xbc, 0x28, 0xa1, 0xf7, 0x4b, 0xd8,
	0xb9, 0x51, 0x93, 0x25, 0xc1, 0xfa, 0x24, 0x1b, 0xac, 0x05, 0x77, 0xa4, 0xb1, 0xeb, 0x99, 0xb0,
	0xb9, 0x5c, 0x89, 0xff, 0x41, 0x28, 0x7b, 0x99, 0x3a, 0xf9, 0x81, 0x02, 0xdd, 0x87, 0xba, 0xa8,
	0x20, 0x2e, 0x30, 0x53, 0xd0, 0x49, 0x89, 0x1a, 0x12, 0xff, 0xde, 0xfa, 0xc3, 0xc3, 0x57, 0x00,
	0xe9, 0xf6, 0x8a, 0x3a, 0x00, 0x47, 0xa7, 0xec, 0xe9, 0x3a, 0x1e, 0x9d, 0xbc, 0x16, 0xd3, 0x86,
	0x1c, 0x2a, 0xf6, 0x7f, 0x6d, 0xa9, 0x79, 0x44, 0x2b, 0xa1, 0x2e, 0xb4, 0x25, 0xe2, 0xd5, 0xe8,
	0x17, 0xfd, 0xc1, 0x6b, 0xad, 0xfc, 0xb0, 0x0f, 0xad, 0xcc, 0xec, 0xce, 0x26, 0x8d, 0x41, 0xdf,
	0x34, 0xfb, 0x27, 0x07, 0x46, 0x5f, 0x5b, 0x41, 0x0d, 0xa8, 0x1e, 0x8e, 0x8e, 0x87, 0x5a, 0x89,
	0x23, 0x4e, 0x07, 0xaf, 0x8d, 0xd3, 0xfe, 0xe0, 0x95, 0x56, 0x46, 0x00, 0x75, 0xf3, 0xcb, 0xe3,
	0xd1, 0xd9, 0x50, 0xab, 0x3c, 0xfd, 0x6b, 0x15, 0x56, 0xf7, 0xb9, 0x09, 0x2e, 0x7a, 0x09, 0x6b,
	0xd9, 0xfd, 0x04, 0x7d, 0xa8, 0x1c, 0xbd, 0xb8, 0xb5, 0xf4, 0x54, 0x14, 0xc4, 0x67, 0xae, 0x15,
	0xf4, 0x1c, 0x5a, 0x99, 0x0f, 0x22, 0x28, 0x8f, 0xef, 0xa9, 0x36, 0x50, 0xfc, 0x68, 0xa2, 0xaf,
	0xa0, 0x17, 0xb0, 0x96, 0xdd, 0x70, 0x8a, 0xac, 0x3b, 0x59, 0xd6, 0xdc, 0x1a, 0xa4, 0xaf, 0xa0,
	0x2f, 0xa0, 0xa9, 0x3e, 0x37, 0x20, 0x75, 0x49, 0xf1, 0x3b, 0x4b, 0x6f, 0x73, 0x09, 0x46, 0x08,
	0x18, 0x42, 0x2b, 0xb3, 0x87, 0x23, 0xb5, 0xc6, 0x2f, 0x7e, 0x8a, 0x48, 0x6d, 0x28, 0x2e, 0xee,
	0xdc, 0x7a, 0x48, 0xb7, 0x73, 0xb4, 0x93, 0x52, 0x16, 0x36, 0xf6, 0x45, 0xbf, 0x0d, 0xa1, 0x95,
	0x59, 0x24, 0x52, 0x05, 0x16, 0xf7, 0xb7, 0x54, 0x81, 0xe2, 0xe6, 0xa1, 0xaf, 0xa0, 0x27, 0x50,
	0xe3, 0x7b, 0x03, 0xba, 0xb3, 0x6c, 0x8d, 0x58, 0xb8, 0xf6, 0x7e, 0x09, 0xed, 0x41, 0xe5, 0x08,
	0x53, 0x84, 0x16, 0x67, 0xce, 0x9e, 0x56, 0x9c, 0xe3, 0xf4, 0x95, 0x27, 0xa5, 0x49, 0x9d, 0x7f,
	0xda, 0x7c, 0xf6, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9a, 0x3b, 0x6f, 0xc7, 0x98, 0x15, 0x00,
	0x00,
}
