// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/CSUNetSec/netsec-protobufs/common/common.proto

package common

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

//
// Capture specification
//
type CaptureSpec_Type int32

const (
	CaptureSpec_FLOW     CaptureSpec_Type = 0
	CaptureSpec_BGP_MRT  CaptureSpec_Type = 1
	CaptureSpec_BGP_LIVE CaptureSpec_Type = 2
)

var CaptureSpec_Type_name = map[int32]string{
	0: "FLOW",
	1: "BGP_MRT",
	2: "BGP_LIVE",
}
var CaptureSpec_Type_value = map[string]int32{
	"FLOW":     0,
	"BGP_MRT":  1,
	"BGP_LIVE": 2,
}

func (x CaptureSpec_Type) String() string {
	return proto.EnumName(CaptureSpec_Type_name, int32(x))
}
func (CaptureSpec_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_common_41437baf8639e274, []int{2, 0}
}

type IPAddressWrapper struct {
	// must be at least one or the other
	IPv4                 []byte   `protobuf:"bytes,1,opt,name=IPv4,proto3" json:"IPv4,omitempty"`
	IPv6                 []byte   `protobuf:"bytes,2,opt,name=IPv6,proto3" json:"IPv6,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IPAddressWrapper) Reset()         { *m = IPAddressWrapper{} }
func (m *IPAddressWrapper) String() string { return proto.CompactTextString(m) }
func (*IPAddressWrapper) ProtoMessage()    {}
func (*IPAddressWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_41437baf8639e274, []int{0}
}
func (m *IPAddressWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IPAddressWrapper.Unmarshal(m, b)
}
func (m *IPAddressWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IPAddressWrapper.Marshal(b, m, deterministic)
}
func (dst *IPAddressWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IPAddressWrapper.Merge(dst, src)
}
func (m *IPAddressWrapper) XXX_Size() int {
	return xxx_messageInfo_IPAddressWrapper.Size(m)
}
func (m *IPAddressWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_IPAddressWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_IPAddressWrapper proto.InternalMessageInfo

func (m *IPAddressWrapper) GetIPv4() []byte {
	if m != nil {
		return m.IPv4
	}
	return nil
}

func (m *IPAddressWrapper) GetIPv6() []byte {
	if m != nil {
		return m.IPv6
	}
	return nil
}

type PrefixWrapper struct {
	// both are really required
	Prefix               *IPAddressWrapper `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Mask                 uint32            `protobuf:"varint,2,opt,name=mask,proto3" json:"mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PrefixWrapper) Reset()         { *m = PrefixWrapper{} }
func (m *PrefixWrapper) String() string { return proto.CompactTextString(m) }
func (*PrefixWrapper) ProtoMessage()    {}
func (*PrefixWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_41437baf8639e274, []int{1}
}
func (m *PrefixWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrefixWrapper.Unmarshal(m, b)
}
func (m *PrefixWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrefixWrapper.Marshal(b, m, deterministic)
}
func (dst *PrefixWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrefixWrapper.Merge(dst, src)
}
func (m *PrefixWrapper) XXX_Size() int {
	return xxx_messageInfo_PrefixWrapper.Size(m)
}
func (m *PrefixWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_PrefixWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_PrefixWrapper proto.InternalMessageInfo

func (m *PrefixWrapper) GetPrefix() *IPAddressWrapper {
	if m != nil {
		return m.Prefix
	}
	return nil
}

func (m *PrefixWrapper) GetMask() uint32 {
	if m != nil {
		return m.Mask
	}
	return 0
}

// We try to keep as much state about the file that we convert as we
// can, so we have some idea of where this data came from and who
// handled it
type CaptureSpec struct {
	// each flow needs a proper id. Such an id is local to the file
	// in which records refer to it. The capture_spec_id is *not* global.
	// Global significance is actually the remainder of the fields.
	CaptureSpecId int32 `protobuf:"varint,1,opt,name=capture_spec_id,json=captureSpecId,proto3" json:"capture_spec_id,omitempty"`
	// Some applications, e.g., BGP may be logging verbose debugging
	// ID's instead of doing a lookup on the capture_spec id above.
	// the caputre spec and debug_id should have a 1-1 mapping between
	// them, but the verbose debug id is self-contained.
	VerboseDebugId    []byte           `protobuf:"bytes,12,opt,name=verbose_debug_id,json=verboseDebugId,proto3" json:"verbose_debug_id,omitempty"`
	Type              CaptureSpec_Type `protobuf:"varint,14,opt,name=type,proto3,enum=common.CaptureSpec_Type" json:"type,omitempty"`
	TcpdumpExpression string           `protobuf:"bytes,2,opt,name=tcpdump_expression,json=tcpdumpExpression,proto3" json:"tcpdump_expression,omitempty"`
	// What is the location of the capture in string format
	// AT&T West LAX POP 1123231
	CaptureLocation string `protobuf:"bytes,3,opt,name=capture_location,json=captureLocation,proto3" json:"capture_location,omitempty"`
	// What is the location in terms of IP
	CaptureLocation_IP *IPAddressWrapper `protobuf:"bytes,4,opt,name=capture_location_IP,json=captureLocationIP,proto3" json:"capture_location_IP,omitempty"`
	// if the capture node has a dns name, this is it
	// FQDN e.g., intercept.ny.nofutz.com
	CaptureLocationDns string `protobuf:"bytes,5,opt,name=capture_location_dns,json=captureLocationDns,proto3" json:"capture_location_dns,omitempty"`
	// if there are multiple capture devices in a location
	// which device is this spec.
	// e.g., capturehost01.intercept.ny.nofutz.com
	CaptureNodeSpec string `protobuf:"bytes,6,opt,name=capture_node_spec,json=captureNodeSpec,proto3" json:"capture_node_spec,omitempty"`
	// The interface on which the data was sniffed
	// ETH10
	CaptureNodeInterface []string `protobuf:"bytes,7,rep,name=capture_node_interface,json=captureNodeInterface,proto3" json:"capture_node_interface,omitempty"`
	// For BGP we may only be capturing a link between this
	// capture location IP and the ptp_peer.
	PtpPeer *IPAddressWrapper `protobuf:"bytes,13,opt,name=ptp_peer,json=ptpPeer,proto3" json:"ptp_peer,omitempty"`
	// Capture retrieval specification. The capture was originally
	// stored somewhere in some file. The original file is identified
	// below. This is important for provenance, e.g., we might have
	// to filter out data that was stored on a compromised host.
	// And if we ever have a bug, this should allow us to reconstruct our
	// state from the source data.
	StorageHost []string `protobuf:"bytes,8,rep,name=storage_host,json=storageHost,proto3" json:"storage_host,omitempty"`
	PathToFiles []string `protobuf:"bytes,9,rep,name=path_to_files,json=pathToFiles,proto3" json:"path_to_files,omitempty"`
	// A pattern that allows us to identify the sequence of files. The
	// expression is expected to be a PCRE expression.
	//    http://www.pcre.org/current/doc/html/
	//
	// For example, "capture_(%d+)" says that the files are named
	// capture with the sequence number appended after the _
	FilePattern []string `protobuf:"bytes,10,rep,name=file_pattern,json=filePattern,proto3" json:"file_pattern,omitempty"`
	// Username of the file owner
	Username             string   `protobuf:"bytes,11,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CaptureSpec) Reset()         { *m = CaptureSpec{} }
func (m *CaptureSpec) String() string { return proto.CompactTextString(m) }
func (*CaptureSpec) ProtoMessage()    {}
func (*CaptureSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_41437baf8639e274, []int{2}
}
func (m *CaptureSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CaptureSpec.Unmarshal(m, b)
}
func (m *CaptureSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CaptureSpec.Marshal(b, m, deterministic)
}
func (dst *CaptureSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CaptureSpec.Merge(dst, src)
}
func (m *CaptureSpec) XXX_Size() int {
	return xxx_messageInfo_CaptureSpec.Size(m)
}
func (m *CaptureSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_CaptureSpec.DiscardUnknown(m)
}

var xxx_messageInfo_CaptureSpec proto.InternalMessageInfo

func (m *CaptureSpec) GetCaptureSpecId() int32 {
	if m != nil {
		return m.CaptureSpecId
	}
	return 0
}

func (m *CaptureSpec) GetVerboseDebugId() []byte {
	if m != nil {
		return m.VerboseDebugId
	}
	return nil
}

func (m *CaptureSpec) GetType() CaptureSpec_Type {
	if m != nil {
		return m.Type
	}
	return CaptureSpec_FLOW
}

func (m *CaptureSpec) GetTcpdumpExpression() string {
	if m != nil {
		return m.TcpdumpExpression
	}
	return ""
}

func (m *CaptureSpec) GetCaptureLocation() string {
	if m != nil {
		return m.CaptureLocation
	}
	return ""
}

func (m *CaptureSpec) GetCaptureLocation_IP() *IPAddressWrapper {
	if m != nil {
		return m.CaptureLocation_IP
	}
	return nil
}

func (m *CaptureSpec) GetCaptureLocationDns() string {
	if m != nil {
		return m.CaptureLocationDns
	}
	return ""
}

func (m *CaptureSpec) GetCaptureNodeSpec() string {
	if m != nil {
		return m.CaptureNodeSpec
	}
	return ""
}

func (m *CaptureSpec) GetCaptureNodeInterface() []string {
	if m != nil {
		return m.CaptureNodeInterface
	}
	return nil
}

func (m *CaptureSpec) GetPtpPeer() *IPAddressWrapper {
	if m != nil {
		return m.PtpPeer
	}
	return nil
}

func (m *CaptureSpec) GetStorageHost() []string {
	if m != nil {
		return m.StorageHost
	}
	return nil
}

func (m *CaptureSpec) GetPathToFiles() []string {
	if m != nil {
		return m.PathToFiles
	}
	return nil
}

func (m *CaptureSpec) GetFilePattern() []string {
	if m != nil {
		return m.FilePattern
	}
	return nil
}

func (m *CaptureSpec) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func init() {
	proto.RegisterType((*IPAddressWrapper)(nil), "common.IPAddressWrapper")
	proto.RegisterType((*PrefixWrapper)(nil), "common.PrefixWrapper")
	proto.RegisterType((*CaptureSpec)(nil), "common.CaptureSpec")
	proto.RegisterEnum("common.CaptureSpec_Type", CaptureSpec_Type_name, CaptureSpec_Type_value)
}

func init() {
	proto.RegisterFile("github.com/CSUNetSec/netsec-protobufs/common/common.proto", fileDescriptor_common_41437baf8639e274)
}

var fileDescriptor_common_41437baf8639e274 = []byte{
	// 511 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0x4b, 0x4f, 0xdb, 0x40,
	0x10, 0xc7, 0x1b, 0x08, 0x79, 0x4c, 0x1e, 0x35, 0x5b, 0x54, 0xad, 0x7a, 0x4a, 0x73, 0xa8, 0xd2,
	0x07, 0x09, 0x2a, 0x08, 0xa9, 0xbd, 0xb5, 0x3c, 0x8a, 0xa5, 0x94, 0x5a, 0x4e, 0x28, 0xc7, 0x95,
	0xb3, 0x9e, 0x24, 0x56, 0xb1, 0x77, 0xb5, 0xbb, 0x46, 0xf0, 0xa1, 0xfa, 0x1d, 0xab, 0x5d, 0x3b,
	0x01, 0xd2, 0x03, 0x27, 0xef, 0xfc, 0xe6, 0x3f, 0xff, 0x99, 0x59, 0xdb, 0xf0, 0x65, 0x91, 0x98,
	0x65, 0x3e, 0x1b, 0x72, 0x91, 0x8e, 0x4e, 0x26, 0x57, 0x97, 0x68, 0x26, 0xc8, 0x47, 0x19, 0x1a,
	0x8d, 0x7c, 0x5f, 0x2a, 0x61, 0xc4, 0x2c, 0x9f, 0xeb, 0x11, 0x17, 0x69, 0x2a, 0xb2, 0xf2, 0x31,
	0x74, 0x9c, 0xd4, 0x8a, 0xa8, 0xff, 0x15, 0x3c, 0x3f, 0xf8, 0x16, 0xc7, 0x0a, 0xb5, 0xbe, 0x56,
	0x91, 0x94, 0xa8, 0x08, 0x81, 0xaa, 0x1f, 0xdc, 0x1e, 0xd1, 0x4a, 0xaf, 0x32, 0x68, 0x87, 0xee,
	0x5c, 0xb2, 0x63, 0xba, 0xb5, 0x66, 0xc7, 0xfd, 0x2b, 0xe8, 0x04, 0x0a, 0xe7, 0xc9, 0xdd, 0xaa,
	0xf0, 0x00, 0x6a, 0xd2, 0x01, 0x57, 0xda, 0xfa, 0x4c, 0x87, 0x65, 0xcf, 0xcd, 0x16, 0x61, 0xa9,
	0xb3, 0xb6, 0x69, 0xa4, 0xff, 0x38, 0xdb, 0x4e, 0xe8, 0xce, 0xfd, 0xbf, 0x3b, 0xd0, 0x3a, 0x89,
	0xa4, 0xc9, 0x15, 0x4e, 0x24, 0x72, 0xf2, 0x0e, 0x5e, 0xf2, 0x22, 0x64, 0x5a, 0x22, 0x67, 0x49,
	0xec, 0xec, 0x77, 0xc2, 0x0e, 0x7f, 0x50, 0xf9, 0x31, 0x19, 0x80, 0x77, 0x8b, 0x6a, 0x26, 0x34,
	0xb2, 0x18, 0x67, 0xf9, 0xc2, 0x0a, 0xdb, 0x6e, 0xdc, 0x6e, 0xc9, 0x4f, 0x2d, 0xf6, 0x63, 0xf2,
	0x09, 0xaa, 0xe6, 0x5e, 0x22, 0xed, 0xf6, 0x2a, 0x83, 0xee, 0xc3, 0x94, 0x8f, 0x9a, 0x0e, 0xa7,
	0xf7, 0x12, 0x43, 0xa7, 0x22, 0xfb, 0x40, 0x0c, 0x97, 0x71, 0x9e, 0x4a, 0x86, 0x77, 0xd2, 0x6e,
	0x91, 0x88, 0xcc, 0x4d, 0xdc, 0x0c, 0x77, 0xcb, 0xcc, 0xd9, 0x3a, 0x41, 0xde, 0x83, 0xb7, 0x1a,
	0xf7, 0x46, 0xf0, 0xc8, 0x58, 0xf1, 0xb6, 0x13, 0xaf, 0xd6, 0x18, 0x97, 0x98, 0x5c, 0xc0, 0xab,
	0x4d, 0x29, 0xf3, 0x03, 0x5a, 0x7d, 0xe6, 0xf2, 0x76, 0x37, 0x7c, 0xfc, 0x80, 0x1c, 0xc0, 0xde,
	0x7f, 0x4e, 0x71, 0xa6, 0xe9, 0x8e, 0x6b, 0x4c, 0x36, 0x0a, 0x4e, 0x33, 0x4d, 0x3e, 0xc0, 0xca,
	0x86, 0x65, 0x22, 0x2e, 0xae, 0x96, 0xd6, 0x9e, 0xcc, 0x79, 0x29, 0xe2, 0xe2, 0x0d, 0x1c, 0xc1,
	0xeb, 0x27, 0xda, 0x24, 0x33, 0xa8, 0xe6, 0x11, 0x47, 0x5a, 0xef, 0x6d, 0x0f, 0x9a, 0xe1, 0xde,
	0xa3, 0x02, 0x7f, 0x95, 0x23, 0x87, 0xd0, 0x90, 0x46, 0x32, 0x89, 0xa8, 0x68, 0xe7, 0x99, 0x95,
	0xea, 0xd2, 0xc8, 0x00, 0x51, 0x91, 0xb7, 0xd0, 0xd6, 0x46, 0xa8, 0x68, 0x81, 0x6c, 0x29, 0xb4,
	0xa1, 0x0d, 0xd7, 0xa0, 0x55, 0xb2, 0x0b, 0xa1, 0x0d, 0xe9, 0x43, 0x47, 0x46, 0x66, 0xc9, 0x8c,
	0x60, 0xf3, 0xe4, 0x06, 0x35, 0x6d, 0x16, 0x1a, 0x0b, 0xa7, 0xe2, 0xdc, 0x22, 0x6b, 0x63, 0x73,
	0x4c, 0x46, 0xc6, 0xa0, 0xca, 0x28, 0x14, 0x12, 0xcb, 0x82, 0x02, 0x91, 0x37, 0xd0, 0xc8, 0x35,
	0xaa, 0x2c, 0x4a, 0x91, 0xb6, 0xdc, 0xde, 0xeb, 0xb8, 0xff, 0x11, 0xaa, 0xf6, 0x03, 0x20, 0x0d,
	0xa8, 0x9e, 0x8f, 0x7f, 0x5d, 0x7b, 0x2f, 0x48, 0x0b, 0xea, 0xdf, 0x7f, 0x04, 0xec, 0x67, 0x38,
	0xf5, 0x2a, 0xa4, 0x0d, 0x0d, 0x1b, 0x8c, 0xfd, 0xdf, 0x67, 0xde, 0xd6, 0xac, 0xe6, 0xfe, 0xa8,
	0xc3, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6c, 0x6a, 0x9e, 0xbe, 0x8e, 0x03, 0x00, 0x00,
}
