// Code generated by protoc-gen-go.
// source: github.com/CSUNetSec/netsec-protobufs/common/common.proto
// DO NOT EDIT!

/*
Package common is a generated protocol buffer package.

It is generated from these files:
	github.com/CSUNetSec/netsec-protobufs/common/common.proto

It has these top-level messages:
	IPAddressWrapper
	PrefixWrapper
*/
package common

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IPAddressWrapper struct {
	// must be at least one or the other
	Ipv4 []byte `protobuf:"bytes,1,opt,name=ipv4,proto3" json:"ipv4,omitempty"`
	Ipv6 []byte `protobuf:"bytes,2,opt,name=ipv6,proto3" json:"ipv6,omitempty"`
}

func (m *IPAddressWrapper) Reset()                    { *m = IPAddressWrapper{} }
func (m *IPAddressWrapper) String() string            { return proto.CompactTextString(m) }
func (*IPAddressWrapper) ProtoMessage()               {}
func (*IPAddressWrapper) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PrefixWrapper struct {
	// both are really required
	Prefix *IPAddressWrapper `protobuf:"bytes,1,opt,name=prefix" json:"prefix,omitempty"`
	Mask   uint32            `protobuf:"varint,2,opt,name=mask" json:"mask,omitempty"`
}

func (m *PrefixWrapper) Reset()                    { *m = PrefixWrapper{} }
func (m *PrefixWrapper) String() string            { return proto.CompactTextString(m) }
func (*PrefixWrapper) ProtoMessage()               {}
func (*PrefixWrapper) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PrefixWrapper) GetPrefix() *IPAddressWrapper {
	if m != nil {
		return m.Prefix
	}
	return nil
}

func init() {
	proto.RegisterType((*IPAddressWrapper)(nil), "common.IPAddressWrapper")
	proto.RegisterType((*PrefixWrapper)(nil), "common.PrefixWrapper")
}

func init() {
	proto.RegisterFile("github.com/CSUNetSec/netsec-protobufs/common/common.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 170 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xb2, 0x4c, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x77, 0x0e, 0x0e, 0xf5, 0x4b, 0x2d, 0x09, 0x4e, 0x4d,
	0xd6, 0xcf, 0x4b, 0x2d, 0x29, 0x4e, 0x4d, 0xd6, 0x2d, 0x28, 0xca, 0x2f, 0xc9, 0x4f, 0x2a, 0x4d,
	0x2b, 0xd6, 0x07, 0x4a, 0xe7, 0xe6, 0xe7, 0x41, 0x29, 0x3d, 0xb0, 0xb8, 0x10, 0x1b, 0x84, 0xa7,
	0x64, 0xc5, 0x25, 0xe0, 0x19, 0xe0, 0x98, 0x92, 0x52, 0x94, 0x5a, 0x5c, 0x1c, 0x5e, 0x94, 0x58,
	0x50, 0x90, 0x5a, 0x24, 0x24, 0xc4, 0xc5, 0x92, 0x59, 0x50, 0x66, 0x22, 0xc1, 0xa8, 0xc0, 0xa8,
	0xc1, 0x13, 0x04, 0x66, 0x43, 0xc5, 0xcc, 0x24, 0x98, 0xe0, 0x62, 0x66, 0x4a, 0xa1, 0x5c, 0xbc,
	0x01, 0x45, 0xa9, 0x69, 0x99, 0x15, 0x30, 0x8d, 0x06, 0x5c, 0x6c, 0x05, 0x60, 0x01, 0xb0, 0x56,
	0x6e, 0x23, 0x09, 0x3d, 0xa8, 0x9d, 0xe8, 0x56, 0x04, 0x41, 0xd5, 0x81, 0x8c, 0xcd, 0x4d, 0x2c,
	0xce, 0x06, 0x1b, 0xcb, 0x1b, 0x04, 0x66, 0x27, 0xb1, 0x81, 0x5d, 0x68, 0x0c, 0x08, 0x00, 0x00,
	0xff, 0xff, 0xa7, 0x36, 0x7f, 0x7d, 0xde, 0x00, 0x00, 0x00,
}
