// Code generated by protoc-gen-go.
// source: github.com/CSUNetSec/netsec-protobufs/proddle/proddle.proto
// DO NOT EDIT!

/*
Package proddle is a generated protocol buffer package.

It is generated from these files:
	github.com/CSUNetSec/netsec-protobufs/proddle/proddle.proto

It has these top-level messages:
	Probe
	ProbeResult
	CancelProbeRequest
	CancelProbeReply
	SearchRequest
	SearchReply
	ScheduleProbeRequest
	ScheduleProbeReply
	BucketHash
	BucketProbes
	GetProbesRequest
	GetProbesReply
	GetBucketKeysRequest
	GetBucketKeysReply
	SendProbeResultsRequest
	SendProbeResultsReply
*/
package proddle

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
// probe messages
type Protocol int32

const (
	Protocol_DNS        Protocol = 0
	Protocol_HTTP       Protocol = 1
	Protocol_HTTPS      Protocol = 2
	Protocol_PING       Protocol = 3
	Protocol_TRACEROUTE Protocol = 4
)

var Protocol_name = map[int32]string{
	0: "DNS",
	1: "HTTP",
	2: "HTTPS",
	3: "PING",
	4: "TRACEROUTE",
}
var Protocol_value = map[string]int32{
	"DNS":        0,
	"HTTP":       1,
	"HTTPS":      2,
	"PING":       3,
	"TRACEROUTE": 4,
}

func (x Protocol) String() string {
	return proto.EnumName(Protocol_name, int32(x))
}
func (Protocol) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Probe struct {
	ProbeId                  uint64   `protobuf:"varint,1,opt,name=probe_id,json=probeId" json:"probe_id,omitempty"`
	ProbeIntervalSeconds     uint32   `protobuf:"varint,2,opt,name=probe_interval_seconds,json=probeIntervalSeconds" json:"probe_interval_seconds,omitempty"`
	TimeoutSeconds           uint32   `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds" json:"timeout_seconds,omitempty"`
	AttemptsToDeclareFailure uint32   `protobuf:"varint,4,opt,name=attempts_to_declare_failure,json=attemptsToDeclareFailure" json:"attempts_to_declare_failure,omitempty"`
	Protocol                 Protocol `protobuf:"varint,5,opt,name=protocol,enum=proddle.Protocol" json:"protocol,omitempty"`
	Domain                   string   `protobuf:"bytes,6,opt,name=domain" json:"domain,omitempty"`
	// HTTP/HTTPS specific
	Port           uint32 `protobuf:"varint,7,opt,name=port" json:"port,omitempty"`
	UrlSuffix      string `protobuf:"bytes,8,opt,name=url_suffix,json=urlSuffix" json:"url_suffix,omitempty"`
	FollowRedirect bool   `protobuf:"varint,9,opt,name=follow_redirect,json=followRedirect" json:"follow_redirect,omitempty"`
}

func (m *Probe) Reset()                    { *m = Probe{} }
func (m *Probe) String() string            { return proto.CompactTextString(m) }
func (*Probe) ProtoMessage()               {}
func (*Probe) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Probe) GetProbeId() uint64 {
	if m != nil {
		return m.ProbeId
	}
	return 0
}

func (m *Probe) GetProbeIntervalSeconds() uint32 {
	if m != nil {
		return m.ProbeIntervalSeconds
	}
	return 0
}

func (m *Probe) GetTimeoutSeconds() uint32 {
	if m != nil {
		return m.TimeoutSeconds
	}
	return 0
}

func (m *Probe) GetAttemptsToDeclareFailure() uint32 {
	if m != nil {
		return m.AttemptsToDeclareFailure
	}
	return 0
}

func (m *Probe) GetProtocol() Protocol {
	if m != nil {
		return m.Protocol
	}
	return Protocol_DNS
}

func (m *Probe) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *Probe) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Probe) GetUrlSuffix() string {
	if m != nil {
		return m.UrlSuffix
	}
	return ""
}

func (m *Probe) GetFollowRedirect() bool {
	if m != nil {
		return m.FollowRedirect
	}
	return false
}

type ProbeResult struct {
	ProbeId                        uint64   `protobuf:"varint,1,opt,name=probe_id,json=probeId" json:"probe_id,omitempty"`
	ProberHostname                 string   `protobuf:"bytes,2,opt,name=prober_hostname,json=proberHostname" json:"prober_hostname,omitempty"`
	Protocol                       Protocol `protobuf:"varint,3,opt,name=protocol,enum=proddle.Protocol" json:"protocol,omitempty"`
	TimestampSec                   uint64   `protobuf:"varint,4,opt,name=timestamp_sec,json=timestampSec" json:"timestamp_sec,omitempty"`
	Success                        bool     `protobuf:"varint,5,opt,name=success" json:"success,omitempty"`
	ErrorMessage                   string   `protobuf:"bytes,6,opt,name=error_message,json=errorMessage" json:"error_message,omitempty"`
	ApplicationLayerLatencyNanosec uint64   `protobuf:"varint,7,opt,name=application_layer_latency_nanosec,json=applicationLayerLatencyNanosec" json:"application_layer_latency_nanosec,omitempty"`
	// DNS specific
	DnsAnswer [][]byte `protobuf:"bytes,8,rep,name=dns_answer,json=dnsAnswer,proto3" json:"dns_answer,omitempty"`
	// HTTP/HTTPS specific
	HttpStatusCode           uint32 `protobuf:"varint,9,opt,name=http_status_code,json=httpStatusCode" json:"http_status_code,omitempty"`
	HttpStatusMessage        string `protobuf:"bytes,10,opt,name=http_status_message,json=httpStatusMessage" json:"http_status_message,omitempty"`
	ApplicationBytesReceived uint32 `protobuf:"varint,11,opt,name=application_bytes_received,json=applicationBytesReceived" json:"application_bytes_received,omitempty"`
}

func (m *ProbeResult) Reset()                    { *m = ProbeResult{} }
func (m *ProbeResult) String() string            { return proto.CompactTextString(m) }
func (*ProbeResult) ProtoMessage()               {}
func (*ProbeResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ProbeResult) GetProbeId() uint64 {
	if m != nil {
		return m.ProbeId
	}
	return 0
}

func (m *ProbeResult) GetProberHostname() string {
	if m != nil {
		return m.ProberHostname
	}
	return ""
}

func (m *ProbeResult) GetProtocol() Protocol {
	if m != nil {
		return m.Protocol
	}
	return Protocol_DNS
}

func (m *ProbeResult) GetTimestampSec() uint64 {
	if m != nil {
		return m.TimestampSec
	}
	return 0
}

func (m *ProbeResult) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ProbeResult) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *ProbeResult) GetApplicationLayerLatencyNanosec() uint64 {
	if m != nil {
		return m.ApplicationLayerLatencyNanosec
	}
	return 0
}

func (m *ProbeResult) GetDnsAnswer() [][]byte {
	if m != nil {
		return m.DnsAnswer
	}
	return nil
}

func (m *ProbeResult) GetHttpStatusCode() uint32 {
	if m != nil {
		return m.HttpStatusCode
	}
	return 0
}

func (m *ProbeResult) GetHttpStatusMessage() string {
	if m != nil {
		return m.HttpStatusMessage
	}
	return ""
}

func (m *ProbeResult) GetApplicationBytesReceived() uint32 {
	if m != nil {
		return m.ApplicationBytesReceived
	}
	return 0
}

type CancelProbeRequest struct {
	Domain   string     `protobuf:"bytes,1,opt,name=domain" json:"domain,omitempty"`
	Protocol []Protocol `protobuf:"varint,2,rep,packed,name=protocol,enum=proddle.Protocol" json:"protocol,omitempty"`
	// HTTP specific
	UrlSuffix string `protobuf:"bytes,3,opt,name=url_suffix,json=urlSuffix" json:"url_suffix,omitempty"`
}

func (m *CancelProbeRequest) Reset()                    { *m = CancelProbeRequest{} }
func (m *CancelProbeRequest) String() string            { return proto.CompactTextString(m) }
func (*CancelProbeRequest) ProtoMessage()               {}
func (*CancelProbeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CancelProbeRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *CancelProbeRequest) GetProtocol() []Protocol {
	if m != nil {
		return m.Protocol
	}
	return nil
}

func (m *CancelProbeRequest) GetUrlSuffix() string {
	if m != nil {
		return m.UrlSuffix
	}
	return ""
}

type CancelProbeReply struct {
}

func (m *CancelProbeReply) Reset()                    { *m = CancelProbeReply{} }
func (m *CancelProbeReply) String() string            { return proto.CompactTextString(m) }
func (*CancelProbeReply) ProtoMessage()               {}
func (*CancelProbeReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type SearchRequest struct {
	Protocol []Protocol `protobuf:"varint,1,rep,packed,name=protocol,enum=proddle.Protocol" json:"protocol,omitempty"`
	Domain   string     `protobuf:"bytes,2,opt,name=domain" json:"domain,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SearchRequest) GetProtocol() []Protocol {
	if m != nil {
		return m.Protocol
	}
	return nil
}

func (m *SearchRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

type SearchReply struct {
	Probe []*Probe `protobuf:"bytes,1,rep,name=probe" json:"probe,omitempty"`
}

func (m *SearchReply) Reset()                    { *m = SearchReply{} }
func (m *SearchReply) String() string            { return proto.CompactTextString(m) }
func (*SearchReply) ProtoMessage()               {}
func (*SearchReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SearchReply) GetProbe() []*Probe {
	if m != nil {
		return m.Probe
	}
	return nil
}

type ScheduleProbeRequest struct {
	Probe []*Probe `protobuf:"bytes,2,rep,name=probe" json:"probe,omitempty"`
}

func (m *ScheduleProbeRequest) Reset()                    { *m = ScheduleProbeRequest{} }
func (m *ScheduleProbeRequest) String() string            { return proto.CompactTextString(m) }
func (*ScheduleProbeRequest) ProtoMessage()               {}
func (*ScheduleProbeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ScheduleProbeRequest) GetProbe() []*Probe {
	if m != nil {
		return m.Probe
	}
	return nil
}

type ScheduleProbeReply struct {
}

func (m *ScheduleProbeReply) Reset()                    { *m = ScheduleProbeReply{} }
func (m *ScheduleProbeReply) String() string            { return proto.CompactTextString(m) }
func (*ScheduleProbeReply) ProtoMessage()               {}
func (*ScheduleProbeReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type BucketHash struct {
	BucketKey uint64 `protobuf:"varint,1,opt,name=bucket_key,json=bucketKey" json:"bucket_key,omitempty"`
	Hash      uint64 `protobuf:"varint,2,opt,name=hash" json:"hash,omitempty"`
}

func (m *BucketHash) Reset()                    { *m = BucketHash{} }
func (m *BucketHash) String() string            { return proto.CompactTextString(m) }
func (*BucketHash) ProtoMessage()               {}
func (*BucketHash) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *BucketHash) GetBucketKey() uint64 {
	if m != nil {
		return m.BucketKey
	}
	return 0
}

func (m *BucketHash) GetHash() uint64 {
	if m != nil {
		return m.Hash
	}
	return 0
}

type BucketProbes struct {
	BucketKey uint64   `protobuf:"varint,1,opt,name=bucket_key,json=bucketKey" json:"bucket_key,omitempty"`
	Probe     []*Probe `protobuf:"bytes,2,rep,name=probe" json:"probe,omitempty"`
}

func (m *BucketProbes) Reset()                    { *m = BucketProbes{} }
func (m *BucketProbes) String() string            { return proto.CompactTextString(m) }
func (*BucketProbes) ProtoMessage()               {}
func (*BucketProbes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *BucketProbes) GetBucketKey() uint64 {
	if m != nil {
		return m.BucketKey
	}
	return 0
}

func (m *BucketProbes) GetProbe() []*Probe {
	if m != nil {
		return m.Probe
	}
	return nil
}

type GetProbesRequest struct {
	BucketHash []*BucketHash `protobuf:"bytes,1,rep,name=bucket_hash,json=bucketHash" json:"bucket_hash,omitempty"`
}

func (m *GetProbesRequest) Reset()                    { *m = GetProbesRequest{} }
func (m *GetProbesRequest) String() string            { return proto.CompactTextString(m) }
func (*GetProbesRequest) ProtoMessage()               {}
func (*GetProbesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *GetProbesRequest) GetBucketHash() []*BucketHash {
	if m != nil {
		return m.BucketHash
	}
	return nil
}

type GetProbesReply struct {
	BucketProbes []*BucketProbes `protobuf:"bytes,1,rep,name=bucket_probes,json=bucketProbes" json:"bucket_probes,omitempty"`
}

func (m *GetProbesReply) Reset()                    { *m = GetProbesReply{} }
func (m *GetProbesReply) String() string            { return proto.CompactTextString(m) }
func (*GetProbesReply) ProtoMessage()               {}
func (*GetProbesReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *GetProbesReply) GetBucketProbes() []*BucketProbes {
	if m != nil {
		return m.BucketProbes
	}
	return nil
}

type GetBucketKeysRequest struct {
}

func (m *GetBucketKeysRequest) Reset()                    { *m = GetBucketKeysRequest{} }
func (m *GetBucketKeysRequest) String() string            { return proto.CompactTextString(m) }
func (*GetBucketKeysRequest) ProtoMessage()               {}
func (*GetBucketKeysRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type GetBucketKeysReply struct {
	BucketKey []uint64 `protobuf:"varint,1,rep,packed,name=bucket_key,json=bucketKey" json:"bucket_key,omitempty"`
}

func (m *GetBucketKeysReply) Reset()                    { *m = GetBucketKeysReply{} }
func (m *GetBucketKeysReply) String() string            { return proto.CompactTextString(m) }
func (*GetBucketKeysReply) ProtoMessage()               {}
func (*GetBucketKeysReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *GetBucketKeysReply) GetBucketKey() []uint64 {
	if m != nil {
		return m.BucketKey
	}
	return nil
}

type SendProbeResultsRequest struct {
	ProbeResult []*ProbeResult `protobuf:"bytes,1,rep,name=probe_result,json=probeResult" json:"probe_result,omitempty"`
}

func (m *SendProbeResultsRequest) Reset()                    { *m = SendProbeResultsRequest{} }
func (m *SendProbeResultsRequest) String() string            { return proto.CompactTextString(m) }
func (*SendProbeResultsRequest) ProtoMessage()               {}
func (*SendProbeResultsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *SendProbeResultsRequest) GetProbeResult() []*ProbeResult {
	if m != nil {
		return m.ProbeResult
	}
	return nil
}

type SendProbeResultsReply struct {
}

func (m *SendProbeResultsReply) Reset()                    { *m = SendProbeResultsReply{} }
func (m *SendProbeResultsReply) String() string            { return proto.CompactTextString(m) }
func (*SendProbeResultsReply) ProtoMessage()               {}
func (*SendProbeResultsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func init() {
	proto.RegisterType((*Probe)(nil), "proddle.Probe")
	proto.RegisterType((*ProbeResult)(nil), "proddle.ProbeResult")
	proto.RegisterType((*CancelProbeRequest)(nil), "proddle.CancelProbeRequest")
	proto.RegisterType((*CancelProbeReply)(nil), "proddle.CancelProbeReply")
	proto.RegisterType((*SearchRequest)(nil), "proddle.SearchRequest")
	proto.RegisterType((*SearchReply)(nil), "proddle.SearchReply")
	proto.RegisterType((*ScheduleProbeRequest)(nil), "proddle.ScheduleProbeRequest")
	proto.RegisterType((*ScheduleProbeReply)(nil), "proddle.ScheduleProbeReply")
	proto.RegisterType((*BucketHash)(nil), "proddle.BucketHash")
	proto.RegisterType((*BucketProbes)(nil), "proddle.BucketProbes")
	proto.RegisterType((*GetProbesRequest)(nil), "proddle.GetProbesRequest")
	proto.RegisterType((*GetProbesReply)(nil), "proddle.GetProbesReply")
	proto.RegisterType((*GetBucketKeysRequest)(nil), "proddle.GetBucketKeysRequest")
	proto.RegisterType((*GetBucketKeysReply)(nil), "proddle.GetBucketKeysReply")
	proto.RegisterType((*SendProbeResultsRequest)(nil), "proddle.SendProbeResultsRequest")
	proto.RegisterType((*SendProbeResultsReply)(nil), "proddle.SendProbeResultsReply")
	proto.RegisterEnum("proddle.Protocol", Protocol_name, Protocol_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Scheduler service

type SchedulerClient interface {
	CancelProbe(ctx context.Context, in *CancelProbeRequest, opts ...grpc.CallOption) (*CancelProbeReply, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchReply, error)
	ScheduleProbe(ctx context.Context, in *ScheduleProbeRequest, opts ...grpc.CallOption) (*ScheduleProbeReply, error)
}

type schedulerClient struct {
	cc *grpc.ClientConn
}

func NewSchedulerClient(cc *grpc.ClientConn) SchedulerClient {
	return &schedulerClient{cc}
}

func (c *schedulerClient) CancelProbe(ctx context.Context, in *CancelProbeRequest, opts ...grpc.CallOption) (*CancelProbeReply, error) {
	out := new(CancelProbeReply)
	err := grpc.Invoke(ctx, "/proddle.Scheduler/CancelProbe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchReply, error) {
	out := new(SearchReply)
	err := grpc.Invoke(ctx, "/proddle.Scheduler/Search", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) ScheduleProbe(ctx context.Context, in *ScheduleProbeRequest, opts ...grpc.CallOption) (*ScheduleProbeReply, error) {
	out := new(ScheduleProbeReply)
	err := grpc.Invoke(ctx, "/proddle.Scheduler/ScheduleProbe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Scheduler service

type SchedulerServer interface {
	CancelProbe(context.Context, *CancelProbeRequest) (*CancelProbeReply, error)
	Search(context.Context, *SearchRequest) (*SearchReply, error)
	ScheduleProbe(context.Context, *ScheduleProbeRequest) (*ScheduleProbeReply, error)
}

func RegisterSchedulerServer(s *grpc.Server, srv SchedulerServer) {
	s.RegisterService(&_Scheduler_serviceDesc, srv)
}

func _Scheduler_CancelProbe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelProbeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).CancelProbe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proddle.Scheduler/CancelProbe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).CancelProbe(ctx, req.(*CancelProbeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proddle.Scheduler/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_ScheduleProbe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleProbeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).ScheduleProbe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proddle.Scheduler/ScheduleProbe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).ScheduleProbe(ctx, req.(*ScheduleProbeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Scheduler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proddle.Scheduler",
	HandlerType: (*SchedulerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CancelProbe",
			Handler:    _Scheduler_CancelProbe_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _Scheduler_Search_Handler,
		},
		{
			MethodName: "ScheduleProbe",
			Handler:    _Scheduler_ScheduleProbe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/CSUNetSec/netsec-protobufs/proddle/proddle.proto",
}

// Client API for ProbeCache service

type ProbeCacheClient interface {
	GetProbes(ctx context.Context, in *GetProbesRequest, opts ...grpc.CallOption) (*GetProbesReply, error)
	GetBucketKeys(ctx context.Context, in *GetBucketKeysRequest, opts ...grpc.CallOption) (*GetBucketKeysReply, error)
	SendProbeResults(ctx context.Context, in *SendProbeResultsRequest, opts ...grpc.CallOption) (*SendProbeResultsReply, error)
}

type probeCacheClient struct {
	cc *grpc.ClientConn
}

func NewProbeCacheClient(cc *grpc.ClientConn) ProbeCacheClient {
	return &probeCacheClient{cc}
}

func (c *probeCacheClient) GetProbes(ctx context.Context, in *GetProbesRequest, opts ...grpc.CallOption) (*GetProbesReply, error) {
	out := new(GetProbesReply)
	err := grpc.Invoke(ctx, "/proddle.ProbeCache/GetProbes", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *probeCacheClient) GetBucketKeys(ctx context.Context, in *GetBucketKeysRequest, opts ...grpc.CallOption) (*GetBucketKeysReply, error) {
	out := new(GetBucketKeysReply)
	err := grpc.Invoke(ctx, "/proddle.ProbeCache/GetBucketKeys", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *probeCacheClient) SendProbeResults(ctx context.Context, in *SendProbeResultsRequest, opts ...grpc.CallOption) (*SendProbeResultsReply, error) {
	out := new(SendProbeResultsReply)
	err := grpc.Invoke(ctx, "/proddle.ProbeCache/SendProbeResults", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ProbeCache service

type ProbeCacheServer interface {
	GetProbes(context.Context, *GetProbesRequest) (*GetProbesReply, error)
	GetBucketKeys(context.Context, *GetBucketKeysRequest) (*GetBucketKeysReply, error)
	SendProbeResults(context.Context, *SendProbeResultsRequest) (*SendProbeResultsReply, error)
}

func RegisterProbeCacheServer(s *grpc.Server, srv ProbeCacheServer) {
	s.RegisterService(&_ProbeCache_serviceDesc, srv)
}

func _ProbeCache_GetProbes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProbesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProbeCacheServer).GetProbes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proddle.ProbeCache/GetProbes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProbeCacheServer).GetProbes(ctx, req.(*GetProbesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProbeCache_GetBucketKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBucketKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProbeCacheServer).GetBucketKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proddle.ProbeCache/GetBucketKeys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProbeCacheServer).GetBucketKeys(ctx, req.(*GetBucketKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProbeCache_SendProbeResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendProbeResultsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProbeCacheServer).SendProbeResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proddle.ProbeCache/SendProbeResults",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProbeCacheServer).SendProbeResults(ctx, req.(*SendProbeResultsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProbeCache_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proddle.ProbeCache",
	HandlerType: (*ProbeCacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProbes",
			Handler:    _ProbeCache_GetProbes_Handler,
		},
		{
			MethodName: "GetBucketKeys",
			Handler:    _ProbeCache_GetBucketKeys_Handler,
		},
		{
			MethodName: "SendProbeResults",
			Handler:    _ProbeCache_SendProbeResults_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/CSUNetSec/netsec-protobufs/proddle/proddle.proto",
}

func init() {
	proto.RegisterFile("github.com/CSUNetSec/netsec-protobufs/proddle/proddle.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 965 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x54, 0x5d, 0x6f, 0xdb, 0x36,
	0x14, 0xad, 0x3f, 0x12, 0xdb, 0xd7, 0x8e, 0xa7, 0xb2, 0x6e, 0xa2, 0x3a, 0x68, 0xd1, 0x69, 0x03,
	0x16, 0x0c, 0x68, 0x02, 0xa4, 0x05, 0x36, 0x6c, 0x1d, 0x86, 0xc4, 0xed, 0x92, 0x60, 0x69, 0x16,
	0x50, 0x6e, 0x5f, 0x05, 0x5a, 0xa2, 0x6b, 0xa1, 0xb2, 0xa8, 0x89, 0x54, 0x3b, 0xef, 0xbf, 0xee,
	0x69, 0xc0, 0x7e, 0xc2, 0x9e, 0x47, 0x52, 0x94, 0x2c, 0x3b, 0x5e, 0xd2, 0x27, 0x91, 0xe7, 0x1e,
	0x9e, 0x7b, 0xef, 0xe1, 0xa5, 0xe0, 0xc7, 0xf7, 0xa1, 0x98, 0x65, 0x93, 0x43, 0x9f, 0xcd, 0x8f,
	0x46, 0xee, 0xdb, 0x2b, 0x2a, 0x5c, 0xea, 0x1f, 0xc5, 0x54, 0x70, 0xea, 0x3f, 0x4b, 0x52, 0x26,
	0xd8, 0x24, 0x9b, 0xf2, 0x23, 0xb9, 0x0a, 0x82, 0x88, 0x16, 0xdf, 0x43, 0x1d, 0x41, 0x2d, 0xb3,
	0x75, 0xfe, 0xae, 0xc3, 0xd6, 0x75, 0xca, 0x26, 0x14, 0x3d, 0x82, 0x76, 0xa2, 0x16, 0x5e, 0x18,
	0xd8, 0xb5, 0xa7, 0xb5, 0x83, 0x26, 0x6e, 0xe9, 0xfd, 0x45, 0x80, 0x5e, 0xc0, 0xae, 0x09, 0xc5,
	0x82, 0xa6, 0x1f, 0x49, 0xe4, 0xc9, 0x1c, 0x2c, 0x0e, 0xb8, 0x5d, 0x97, 0xc4, 0x1d, 0x3c, 0xc8,
	0x89, 0x26, 0xe8, 0xe6, 0x31, 0xf4, 0x0d, 0x7c, 0x21, 0xc2, 0x39, 0x65, 0x99, 0x28, 0xe9, 0x0d,
	0x4d, 0xef, 0x1b, 0xb8, 0x20, 0xfe, 0x04, 0xfb, 0x44, 0x08, 0x3a, 0x4f, 0x04, 0xf7, 0x04, 0xf3,
	0x02, 0xea, 0x47, 0x24, 0xa5, 0xde, 0x94, 0x84, 0x51, 0x96, 0x52, 0xbb, 0xa9, 0x0f, 0xd9, 0x05,
	0x65, 0xcc, 0x5e, 0xe5, 0x84, 0x5f, 0xf2, 0x38, 0x7a, 0xa6, 0x0b, 0x17, 0xcc, 0x67, 0x91, 0xbd,
	0x25, 0xb9, 0xfd, 0xe3, 0xfb, 0x87, 0x45, 0xb7, 0xd7, 0x26, 0x80, 0x4b, 0x0a, 0xda, 0x85, 0xed,
	0x80, 0xcd, 0x49, 0x18, 0xdb, 0xdb, 0x92, 0xdc, 0xc1, 0x66, 0x87, 0x10, 0x34, 0x13, 0x96, 0x0a,
	0xbb, 0xa5, 0xd3, 0xe9, 0x35, 0x7a, 0x0c, 0x90, 0xa5, 0xb2, 0xdb, 0x6c, 0x3a, 0x0d, 0xff, 0xb0,
	0xdb, 0x9a, 0xdf, 0x91, 0x88, 0xab, 0x01, 0xd5, 0xe1, 0x94, 0x45, 0x11, 0xfb, 0xe4, 0xa5, 0x34,
	0x08, 0x53, 0xea, 0x0b, 0xbb, 0x23, 0x39, 0x6d, 0xdc, 0xcf, 0x61, 0x6c, 0x50, 0xe7, 0x9f, 0x06,
	0x74, 0xb5, 0xcb, 0x98, 0xf2, 0x2c, 0x12, 0xb7, 0x79, 0x2d, 0x35, 0xf5, 0x32, 0xf5, 0x66, 0x8c,
	0x8b, 0x98, 0xcc, 0xa9, 0x36, 0xb9, 0x83, 0xfb, 0x39, 0x7c, 0x6e, 0xd0, 0x95, 0xb6, 0x1b, 0x77,
	0xb7, 0xfd, 0x15, 0xec, 0x28, 0xdb, 0xb9, 0x20, 0xf3, 0x44, 0xdd, 0x87, 0xb6, 0xb5, 0x89, 0x7b,
	0x25, 0x28, 0x6f, 0x03, 0xd9, 0xd0, 0xe2, 0x99, 0xef, 0x53, 0xce, 0xb5, 0x93, 0x6d, 0x5c, 0x6c,
	0xd5, 0x71, 0x9a, 0xa6, 0x2c, 0xf5, 0x24, 0x9b, 0x93, 0xf7, 0xd4, 0x98, 0xd7, 0xd3, 0xe0, 0x9b,
	0x1c, 0x43, 0x17, 0xf0, 0x25, 0x49, 0x92, 0x28, 0xf4, 0x89, 0x08, 0x59, 0xec, 0x45, 0x64, 0x21,
	0xdb, 0x88, 0x88, 0xa0, 0xb1, 0xbf, 0xf0, 0x62, 0x12, 0x33, 0x95, 0xb7, 0xa5, 0xf3, 0x3e, 0xa9,
	0x10, 0x2f, 0x15, 0xef, 0x32, 0xa7, 0x5d, 0xe5, 0x2c, 0xe5, 0x7c, 0x10, 0x73, 0x8f, 0xc4, 0xfc,
	0x13, 0x4d, 0xa5, 0xf3, 0x8d, 0x83, 0x1e, 0xee, 0x48, 0xe4, 0x44, 0x03, 0xe8, 0x00, 0xac, 0x99,
	0x10, 0xb2, 0x11, 0x41, 0x44, 0xc6, 0x3d, 0x9f, 0x05, 0x54, 0x5b, 0x2f, 0x87, 0x4b, 0xe1, 0xae,
	0x86, 0x47, 0x12, 0x45, 0x87, 0xf0, 0xa0, 0xca, 0x2c, 0xca, 0x07, 0x5d, 0xfe, 0xfd, 0x25, 0xb9,
	0xe8, 0xe1, 0x25, 0x0c, 0xab, 0x3d, 0x4c, 0x16, 0x82, 0x72, 0x79, 0xbd, 0x3e, 0x0d, 0x3f, 0xd2,
	0xc0, 0xee, 0x9a, 0x59, 0x5c, 0x32, 0x4e, 0x15, 0x01, 0x9b, 0xb8, 0xf3, 0x27, 0xa0, 0x11, 0x89,
	0x7d, 0x1a, 0x99, 0xdb, 0xfe, 0x3d, 0x93, 0xe6, 0x56, 0x46, 0xae, 0xb6, 0x32, 0x72, 0xd5, 0x2b,
	0xac, 0xcb, 0x16, 0xef, 0xb8, 0xc2, 0xd5, 0x69, 0x6c, 0xac, 0x4d, 0xa3, 0x83, 0xc0, 0x5a, 0xc9,
	0x9d, 0x44, 0x0b, 0xe7, 0x1d, 0xec, 0xb8, 0x94, 0xa4, 0xfe, 0xac, 0x28, 0xa5, 0x9a, 0xb2, 0x76,
	0x77, 0xca, 0x65, 0xe5, 0xf5, 0x6a, 0xe5, 0xce, 0x73, 0xe8, 0x16, 0xba, 0x32, 0x0d, 0xfa, 0x1a,
	0xb6, 0xf4, 0x74, 0x6a, 0xc9, 0xee, 0x71, 0xbf, 0x2a, 0x29, 0x4b, 0xc9, 0x83, 0xce, 0x4b, 0x18,
	0xb8, 0xfe, 0x8c, 0x06, 0x59, 0x44, 0x57, 0xec, 0x29, 0x4f, 0xd7, 0x6f, 0x3b, 0x3d, 0x00, 0xb4,
	0x76, 0x5a, 0x35, 0xf8, 0x33, 0xc0, 0x69, 0xe6, 0x7f, 0xa0, 0xe2, 0x9c, 0xf0, 0x99, 0x72, 0x68,
	0xa2, 0x77, 0xde, 0x07, 0xba, 0x30, 0x2f, 0xab, 0x93, 0x23, 0xbf, 0xd2, 0x85, 0x7a, 0xe2, 0x33,
	0x49, 0xd3, 0xbd, 0x34, 0xb1, 0x5e, 0x3b, 0x2e, 0xf4, 0x72, 0x01, 0x2d, 0xca, 0xef, 0x92, 0xf8,
	0xbc, 0x5a, 0xcf, 0xc1, 0x3a, 0x2b, 0x14, 0x8b, 0x2e, 0x5f, 0x40, 0xd7, 0x08, 0xeb, 0x1a, 0x72,
	0xa7, 0x1e, 0x94, 0xe7, 0x97, 0x5d, 0x60, 0x53, 0x80, 0x5a, 0x3b, 0x97, 0xd0, 0xaf, 0x28, 0x29,
	0xaf, 0x7f, 0x80, 0x1d, 0xa3, 0xa3, 0x73, 0x71, 0xa3, 0xf4, 0x70, 0x4d, 0xc9, 0x1c, 0xe9, 0x4d,
	0x2a, 0x3b, 0x67, 0x17, 0x06, 0x52, 0xed, 0xb4, 0xe8, 0xa6, 0xa8, 0x4d, 0x5e, 0x27, 0x5a, 0xc3,
	0x55, 0xa6, 0x75, 0x2b, 0x1a, 0x2b, 0x56, 0x38, 0x18, 0xf6, 0x5c, 0x1a, 0x07, 0x95, 0xff, 0x5a,
	0xd9, 0xeb, 0x77, 0xd0, 0xcb, 0xff, 0x6f, 0xa9, 0xc6, 0x4d, 0x89, 0x83, 0x35, 0xb3, 0x74, 0x0c,
	0x77, 0x93, 0xe5, 0xc6, 0xd9, 0x83, 0x87, 0x37, 0x35, 0x65, 0x2d, 0xdf, 0x9e, 0x42, 0xbb, 0x18,
	0x4f, 0xd4, 0x82, 0xc6, 0xab, 0x2b, 0xd7, 0xba, 0x87, 0xda, 0xd0, 0x3c, 0x1f, 0x8f, 0xaf, 0xad,
	0x1a, 0xea, 0xc0, 0x96, 0x5a, 0xb9, 0x56, 0x5d, 0x81, 0xd7, 0x17, 0x57, 0x67, 0x56, 0x03, 0xf5,
	0x01, 0xc6, 0xf8, 0x64, 0xf4, 0x1a, 0xff, 0xf6, 0x76, 0xfc, 0xda, 0x6a, 0x1e, 0xff, 0x55, 0x83,
	0x4e, 0x31, 0x42, 0x29, 0x3a, 0x83, 0x6e, 0xe5, 0xb9, 0xa0, 0xfd, 0xb2, 0xb8, 0x9b, 0x0f, 0x78,
	0xf8, 0x68, 0x73, 0x50, 0x0d, 0xe0, 0x3d, 0xf4, 0x3d, 0x6c, 0xe7, 0x6f, 0x01, 0xed, 0x96, 0xb4,
	0x95, 0x47, 0x37, 0x1c, 0xdc, 0xc0, 0xf3, 0x93, 0x6f, 0xe4, 0xeb, 0xac, 0x8e, 0x34, 0x7a, 0xbc,
	0x24, 0x6e, 0x78, 0x28, 0xc3, 0xfd, 0xff, 0x0b, 0x6b, 0xb9, 0xe3, 0x7f, 0x6b, 0x00, 0x1a, 0x18,
	0x11, 0x19, 0x46, 0x27, 0xd0, 0x29, 0x47, 0x07, 0x2d, 0x3b, 0x58, 0x1f, 0xcc, 0xe1, 0xde, 0xa6,
	0x50, 0x59, 0xe0, 0xca, 0x5c, 0x54, 0x0a, 0xdc, 0x34, 0x47, 0x95, 0x02, 0x6f, 0x8e, 0x93, 0x94,
	0x7b, 0x07, 0xd6, 0xfa, 0xed, 0xa2, 0xa7, 0x15, 0x6f, 0x36, 0x0e, 0xd3, 0xf0, 0xc9, 0x2d, 0x0c,
	0xad, 0x3b, 0xd9, 0xd6, 0xff, 0xab, 0xe7, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x01, 0xdb, 0x6c,
	0xe4, 0x13, 0x09, 0x00, 0x00,
}
